### ISSUE TITLE
Updation in `CONTRIBUTING.md` file. Addition of some rules before raising issue to avoid duplicates issue. 

### ISSUE THREAD

**Issue by ArtiGaund** [Trisha-tech/OnlineBookSales#107]
In current CONTRIBUTING.md, their are steps on how a person can make an open source contribution, but people are not checking current running issues and are not reading code bases, which is why there are multiple duplicate issues raised. I am emphasizing points such as checking existing issues to avoid duplicates and reading the base documentation before raising new issues. And  work on only assigned issues.

# Contributing to [Project Name]

First off, thanks for taking the time to contribute! 🎉

The following is a set of guidelines for contributing to [Project Name]. These are mostly guidelines, not rules. Use your best judgment, and feel free to propose changes to this document in a pull request.

### Before You Submit an Issue

- **Check the existing issues** to see if your issue has already been reported. Duplicate issues clutter the issue tracker and make it harder for us to prioritize issues.
- **Search through open and closed issues** to see if your issue has already been addressed.
- **Review the project documentation** to ensure your issue hasn't already been covered.

### How to Submit an Issue

- Use a **clear and descriptive title** for the issue to identify the problem.
- Describe the **exact steps to reproduce the problem**. Include code snippets or links to a repository, if applicable.
- Explain the **expected behavior** and what actually happens.
- Include any **relevant logs or screenshots** that can help us understand and reproduce the issue.
- **Mention the version** of the software you're using and the environment (e.g., operating system, browser) where the issue occurs.

### Before You Submit a Pull Request

- Ensure that your changes are aligned with the project's goals and codebase.
- Write clear and concise commit messages.
- **Test your changes thoroughly**.
- **Update the documentation** if your changes require it.
- Ensure there are no **merge conflicts** with the base branch.

**Comment by Trisha-tech** [comment]
> In current CONTRIBUTING.md, their are steps on how a person can make an open source contribution, but people are not checking current running issues and are not reading code bases, which is why there are multiple duplicate issues raised. I am emphasizing points such as checking existing issues to avoid duplicates and reading the base documentation before raising new issues. And work on only assigned issues.
> 
> # Contributing to [Project Name]
> First off, thanks for taking the time to contribute! 🎉
> 
> The following is a set of guidelines for contributing to [Project Name]. These are mostly guidelines, not rules. Use your best judgment, and feel free to propose changes to this document in a pull request.
> 
> ## Reporting Issues
> ### Before You Submit an Issue
> * **Check the existing issues** to see if your issue has already been reported. Duplicate issues clutter the issue tracker and make it harder for us to prioritize issues.
> * **Search through open and closed issues** to see if your issue has already been addressed.
> * **Review the project documentation** to ensure your issue hasn't already been covered.
> 
> ### How to Submit an Issue
> * Use a **clear and descriptive title** for the issue to identify the problem.
> * Describe the **exact steps to reproduce the problem**. Include code snippets or links to a repository, if applicable.
> * Explain the **expected behavior** and what actually happens.
> * Include any **relevant logs or screenshots** that can help us understand and reproduce the issue.
> * **Mention the version** of the software you're using and the environment (e.g., operating system, browser) where the issue occurs.
> 
> ## Pull Requests
> ### Before You Submit a Pull Request
> * Ensure that your changes are aligned with the project's goals and codebase.
> * Write clear and concise commit messages.
> * **Test your changes thoroughly**.
> * **Update the documentation** if your changes require it.
> * Ensure there are no **merge conflicts** with the base branch.

Hello @ArtiGaund , Go for it
All the Best
