### ISSUE TITLE
Wants to add Models 

### ISSUE THREAD

**Issue by ArtiGaund** [Trisha-tech/OnlineBookSales#11]

**Comment by Puskar-Roy** [comment]
@ArtiGaund hey I'm interested in contributing models to the project. Could you please specify which specific MongoDB models you'd like me to work on? Please assign me to the relevant issue. Looking forward to contributing!"

**Comment by ArtiGaund** [comment]
@Puskar-Roy I am not mentor. Mentor is the who created this repository. I created this issue I want to work on models. Let's see who they are going to assign. I thought we can create issues, may be I am wrong.

**Comment by Trisha-tech** [comment]
> @Puskar-Roy I am not mentor. Mentor is the who created this repository. I created this issue I want to work on models. Let's see who they are going to assign. I thought we can create issues, may be I am wrong.

Which model you have to add? Kindly specify

**Comment by ArtiGaund** [comment]
@Trisha-tech models are already present in there in the code.

**Comment by Trisha-tech** [comment]
> @Trisha-tech models are already present in there in the code.

Yes, I know models are present in the code. 
But my question is which model schema you want to add ? Because customer, product and order schema are already there.

**Comment by ArtiGaund** [comment]
@Trisha-tech Custom and product

**Comment by ArtiGaund** [comment]
@Trisha-tech can I add Wishlist model schema ?

**Comment by kushagravats** [comment]
Hey i can add model in it like an inventory management schema and a pricing optimization schema

**Comment by rawani123** [comment]
i have seen the models You have made we can do change like ,
we can a different model for review as you had directly in it the productSchema,
can add a different orderItem schema also

**Comment by Trisha-tech** [comment]
> @Trisha-tech can I add Wishlist model schema and cart model schema ?

Hello @ArtiGaund , Go for it
All the best

**Comment by ArtiGaund** [comment]
@Trisha-tech its not asssigned.

**Comment by ArtiGaund** [comment]
@Trisha-Tech, it's not assigned; should I still work on it?

**Comment by mihirpatel07a** [comment]
I want to work on this issue please assign me @Trisha-tech
