### ISSUE TITLE
Auto Commenting feature for PR Raised

### ISSUE THREAD

**Issue by Asymtode712** [Trisha-tech/OnlineBookSales#110]
This solution introduces a new GitHub Actions workflow that automatically comments on new and updated pull requests. This feature aims to streamline the contribution process by providing contributors with immediate feedback and guidance upon creating or updating their pull requests.

**Comment by Asymtode712** [comment]
@Trisha-tech Please assign me this issue under GSSOC'24

**Comment by Trisha-tech** [comment]
> @Trisha-tech Please assign me this issue under GSSOC'24

Hello @Asymtode712 , Go for it
All the Best
