### ISSUE TITLE
Add a Pull Request Template

### ISSUE THREAD

**Issue by Asymtode712** [Trisha-tech/OnlineBookSales#119]
**Is your feature request related to a problem? Please describe.**
Yes, the request for adding a pull request template is related to the problem of inconsistent and unclear pull request submissions. Often, pull requests lack necessary details, making it difficult for reviewers to understand the changes, the reasons behind them, and how to test them. This can lead to delays in the review process, increased back-and-forth communication, and potential oversight of critical issues.

**Describe the solution you'd like**
The solution is to implement a standardized pull request template. This template should include sections that prompt the author to provide essential information, such as:

- A brief description of the changes.
- The issue or feature being addressed (linked to relevant issue tracker entries).
- Screenshots or GIFs (if the changes include UI modifications).
- Checklist for confirming code adheres to coding standards, tests are added/updated, and documentation is updated.

**What problem is this feature trying to solve?**
This feature aims to solve the problem of inefficient and unclear pull request submissions by ensuring that all necessary information is provided upfront.

**Comment by Asymtode712** [comment]
@Trisha-tech please assign me this issue under gssoc'24

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Asymtode712** [comment]
@suhanipaliwal sorry but I have already raised this issue and I'm its author

**Comment by Trisha-tech** [comment]
> @Trisha-tech please assign me this issue under gssoc'24

Hello @Asymtode712 , Go for it
All the Best
