### ISSUE TITLE
Add Detail Page as the User Clicks on the Book

### ISSUE THREAD

**Issue by AshAk0** [Trisha-tech/OnlineBookSales#12]
I would like to work on the design when a user clicks a particular book the details of the book could be viewed
-Book Thumbnail
-About the author
-Title of the Book
-Price of the Book with a selection of currencies
-Quantity
-Add to Cart
-Reviews from the Readers
-Book Suggestions

**Comment by Trisha-tech** [comment]
> I would like to work on the design when a user clicks a particular book the details of the book could be viewed -Book Thumbnail -About the author -Title of the Book -Price of the Book with a selection of currencies -Quantity -Add to Cart -Reviews from the Readers -Book Suggestions

Hello @AshAk0 , Go for it
All The best

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Varsani2520** [comment]
Hello @Trisha-tech  i would like to work with you ,please assign me 

i can add the detail page as the user click on specific book 

if user click on specific book then open their detail page 
and display 
-author name
-book description
-book name
-image
-price
-add to cart
-toast for add to payment 


i can able to all the things ,please assign to me .

**Comment by AshAk0** [comment]
@Trisha-tech It says that there is now mongodb url present and i couldn't run the project can you specify the db url

**Comment by AshAk0** [comment]
@Trisha-tech  I have designed the Product Page details if your ok with this design i can start with creating the components
-- I don't know how the nav bar is designed so i just added my own navbar which can be altered later
-- Colors can be altered later as per your need
-- Fonts can also be alteredd but i had a thought that based on the genre the font style can be changed to match the fonts with the genre

![Product Details PageProduct Details Page](https://github.com/Trisha-tech/OnlineBookSales/assets/130728058/54145ffe-965f-4c8a-9931-f300ad792441)

**Comment by AshAk0** [comment]
@Trisha-tech  Can u share the email so that i can invite you to view the design i made in figma. if you are ok with the design i will move forward with coding

**Comment by Sourabh782** [comment]
@Trisha-tech can I work on it? It's one of the must have feature

**Comment by Trisha-tech** [comment]
> @Trisha-tech can I work on it? It's one of the must have feature

Hello @Sourabh782, Go for it
All the Best

**Comment by Sourabh782** [comment]
> > @Trisha-tech can I work on it? It's one of the must have feature
> 
> Hello @Sourabh782, Go for it All the Best

Thanks @Trisha-tech working on it
