### ISSUE TITLE
Adding list of contributors image in readme

### ISSUE THREAD

**Issue by Arpcoder** [Trisha-tech/OnlineBookSales#124]
![image](https://github.com/Trisha-tech/OnlineBookSales/assets/100352419/847e8d13-8aad-4486-a861-ccc13b9ae257)

**Comment by Trisha-tech** [comment]
> ![image](https://private-user-images.githubusercontent.com/100352419/331769176-847e8d13-8aad-4486-a861-ccc13b9ae257.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTI0NjksIm5iZiI6MTcxNjAxMjE2OSwicGF0aCI6Ii8xMDAzNTI0MTkvMzMxNzY5MTc2LTg0N2U4ZDEzLThhYWQtNDQ4Ni1hODYxLWNjYzEzYjlhZTI1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQwNjAyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTk4MWQ4NzNjYjkyY2U0MDQwNzJkZTMxOGM0MjM1NmRmNThjYjQ2Yzg0MjlmZjhkMDk5OTYyN2VhODFkNzcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.anBg5ejS3KGp84umnUgg5uqDzDA9BqfIED2jMI8aw64)

Hello @Arpcoder , Go for it
All the Best
