### ISSUE TITLE
Adding Animations

### ISSUE THREAD

**Issue by MHusain22** [Trisha-tech/OnlineBookSales#133]
**Is your feature request related to a problem? Please describe.**
Animations will make the UI of the website more enhanced.

**Describe the solution you'd like**
I can Add animations to the Page on loading and scrolling just like in my portfolio website https://mhportfolio.vercel.app/. Please assign me this to add new feature.

**Describe alternatives you've considered**
Using vanilla CSS and animations library

I have checked the existing issues *
I have read the Contributing Guidelines *
I have starred the repository *
Working under Gssoc'24

**Comment by Trisha-tech** [comment]
> **Is your feature request related to a problem? Please describe.** Animations will make the UI of the website more enhanced.
> 
> **Describe the solution you'd like** I can Add animations to the Page on loading and scrolling just like in my portfolio website https://mhportfolio.vercel.app/. Please assign me this to add new feature.
> 
> **Describe alternatives you've considered** Using vanilla CSS and animations library
> 
> I have checked the existing issues * I have read the Contributing Guidelines * I have starred the repository * Working under Gssoc'24

Hello @MHusain22 , Go for it
All the Best
