### ISSUE TITLE
want to change Navbar to improve UI

### ISSUE THREAD

**Issue by ASHISH-JHA94** [Trisha-tech/OnlineBookSales#134]
**Is your feature request related to a problem? Please describe.**
We actually have two Navbar ,the one which is currently there is not looking good ,i want to update this

**Describe the solution you'd like**

i have to delete one of them because we actually have two and didn't requre both of them.
![Screenshot 2024-05-16 000518](https://github.com/Trisha-tech/OnlineBookSales/assets/136432304/0a3d095c-7096-47fa-ba45-20b4eddc63fa)

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
improve Navbar
How do we know when the feature is complete?
I will create Navbar and preview it befor creating pull Request.

**Comment by Trisha-tech** [comment]
> **Is your feature request related to a problem? Please describe.** We actually have two Navbar ,the one which is currently there is not looking good ,i want to update this
> 
> **Describe the solution you'd like**
> 
> i have to delete one of them because we actually have two and didn't requre both of them. ![Screenshot 2024-05-16 000518](https://private-user-images.githubusercontent.com/136432304/331984310-0a3d095c-7096-47fa-ba45-20b4eddc63fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTQ5MTAsIm5iZiI6MTcxNjE5NDYxMCwicGF0aCI6Ii8xMzY0MzIzMDQvMzMxOTg0MzEwLTBhM2QwOTVjLTcwOTYtNDdmYS1iYTQ1LTIwYjRlZGRjNjNmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwODQzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGQxYjdhMjJlYjY5YzZhN2EyMWE4NjMyYWQ0N2NlNjMxZmUxMGEzNGU1NTEwOGYxYThkNDhlMWZjYjdlMzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t7dSQs6HhILlMZLSEGYZP_aALkBP3EUtQleWazkhMc8)
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.
> 
> What problem is this feature trying to solve? improve Navbar How do we know when the feature is complete? I will create Navbar and preview it befor creating pull Request.

Hello @ASHISH-JHA94 , Go for it
All the Best

**Comment by tushargupta1504** [comment]
Good Issue.
