### ISSUE TITLE
[FEAT]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [Trisha-tech/OnlineBookSales#140]
#### Currently, the issue template for this repo are not visually appealing, so I want to add it which will look like this 👇

![image](https://github.com/Trisha-tech/OnlineBookSales/assets/73957207/5101917f-0bbb-47c1-ae5b-a6b54ea3a5bf)

- #### Also I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/Trisha-tech/OnlineBookSales/assets/73957207/862278f7-491e-4530-8534-3985c6d871b3)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by Trisha-tech** [comment]
> I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

Hello @TonyStark-47 , Go for it
All the Best

**Comment by TonyStark-47** [comment]
Hey @Trisha-tech, I have raised a PR #144 related to this issue. Please check it out.
