### ISSUE TITLE
Add an eye icon to see the Password

### ISSUE THREAD

**Issue by RithikaSundaram** [Trisha-tech/OnlineBookSales#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

By adding the eye icon in the password field will help the users to verify that they are correctly entering the password or not. This feature will provide the better user experience.

### Use Case

By having the feature of seeing what is entered in the password will enable the user to have the better user experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by RithikaSundaram** [comment]
Please assign this issue to me . i am very eager in working on this issue.

**Comment by nishant0708** [comment]
hey please assign me this issue under gssoc24

**Comment by imvish21** [comment]
Hey, can you please assign me this issue?

**Comment by nishantmakwanaa** [comment]
Please Assign Issur To Me

**Comment by Trisha-tech** [comment]
> Please assign this issue to me . i am very eager in working on this issue.

Hello @RithikaSundaram , Go for it
All the Best

**Comment by GeeekySouro003** [comment]
please assign this issue to me

**Comment by Vaibhavtech2006** [comment]
[Trisha-tech](https://github.com/Trisha-tech)
@Trisha-tech this issue not solved not till know assigned this work to me
