### ISSUE TITLE
[Feature Request]: Implementing Multilingual Support

### ISSUE THREAD

**Issue by Anjankumarkamalapur** [Trisha-tech/OnlineBookSales#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

On exploring the OnlineBookSales, I noticed that it is only available in English. To make it easier for more people to use and understand, I propose developing the website to support multiple languages. This will allow users to choose their preferred language for a better and more accessible experience.

### Use Case

I wanted to make it available in different languages where non-English speaking users can access  and services in their native language.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> On exploring the OnlineBookSales, I noticed that it is only available in English. To make it easier for more people to use and understand, I propose developing the website to support multiple languages. This will allow users to choose their preferred language for a better and more accessible experience.
> 
> ### Use Case
> I wanted to make it available in different languages where non-English speaking users can access and services in their native language.
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Anjankumarkamalapur , Go for it
All the Best

**Comment by IkkiOcean** [comment]
@Trisha-tech Assign this issue to me under GSSOC-ext and hacktoberfest and pls make it at least level 2 or 3

**Comment by Trisha-tech** [comment]
> @Trisha-tech Assign this issue to me under GSSOC-ext and hacktoberfest and pls make it at least level 2 or 3

Hello @IkkiOcean , Go for it
All the Best

**Comment by IkkiOcean** [comment]
> > @Trisha-tech Assign this issue to me under GSSOC-ext and hacktoberfest and pls make it at least level 2 or 3
> 
> Hello @IkkiOcean , Go for it All the Best

I'm gonna PR soon but please make it **Level 3** as  level 1 is not correct for this Issue
