### ISSUE TITLE
Enhancing the read me file 

### ISSUE THREAD

**Issue by Varda003** [Trisha-tech/OnlineBookSales#15]
I can document all the features and tech stack used adding additional info about them and also alternative way is not mentioned to use  the repository. Please assign this issue to me.

**Comment by Trisha-tech** [comment]
Hello @Varda003 , Go for it but don't change anything existing currently.
All the Best

**Comment by Trisha-tech** [comment]
> I can document all the features and tech stack used adding additional info about them and also alternative way is not mentioned to use the repository. Please assign this issue to me.


Hello @Varda003 , Go for it but don't change anything existing currently.
All the Best

**Comment by Varda003** [comment]
please add the level as well @Trisha-tech  as mentioned Pr won't be counted

**Comment by Varda003** [comment]
please add the level to this issue Level 1 , 2 or 3. I asked  in doubt section my Pr won't be counted.
