### ISSUE TITLE
[Feature Request]: Addition of frontend to test in real time rather than local

### ISSUE THREAD

**Issue by NalinDalal** [Trisha-tech/OnlineBookSales#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

See the website is working, i can say that for sure
but the frontend part of the website is missing which will make it's use possible for non technical people

### Use Case

usage by non technical background people

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-06-06 at 15 27 06" src="https://github.com/Trisha-tech/OnlineBookSales/assets/116961144/b5c5626f-b4d8-4811-b460-c178148ce8d8">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> See the website is working, i can say that for sure but the frontend part of the website is missing which will make it's use possible for non technical people
> 
> ### Use Case
> usage by non technical background people
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> <img alt="Screenshot 2024-06-06 at 15 27 06" width="1440" src="https://private-user-images.githubusercontent.com/116961144/337217126-b5c5626f-b4d8-4811-b460-c178148ce8d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjY2NDksIm5iZiI6MTcxNzgyNjM0OSwicGF0aCI6Ii8xMTY5NjExNDQvMzM3MjE3MTI2LWI1YzU2MjZmLWI0ZDgtNDgxMS1iNDYwLWMxNzgxNDhjZThkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNTU5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTlhMmVhMDFiN2JhNTJiNThiOWQ1ZmE2N2E3YjZiMWViNzdkMjk3OTc5MTEyNzU3ZGQ5ZDM4YWMwMzI5MDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.20XDMGoBStKW-LQQ9XnNijV1gTvwGz3tHBy5po5Yj0g">
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @NalinDalal , Go for it 
All the Best
