### ISSUE TITLE
[Documentation Update]: Add License

### ISSUE THREAD

**Issue by Priyanshu2631** [Trisha-tech/OnlineBookSales#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I want to add MIT License to this repository.

### Suggested Change

In my PR, I will add the License file into the repository, so kindly assign me the issue under GSSOC'24.

### Urgency

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Issue Description
> I want to add MIT License to this repository.
> 
> ### Suggested Change
> In my PR, I will add the License file into the repository, so kindly assign me the issue under GSSOC'24.
> 
> ### Rationale
> _No response_
> 
> ### Urgency
> Low
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Priyanshu2631 , Go for it
All the Best

**Comment by Priyanshu2631** [comment]
@Trisha-tech please add labels, I will attach the PR.
