### ISSUE TITLE
[Feature Request]: Greeting on Issue Closure

### ISSUE THREAD

**Issue by thevijayshankersharma** [Trisha-tech/OnlineBookSales#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implementing a greeting message upon issue closure would add a touch of personalization and acknowledgment to the collaboration process within a project's issue tracker. This feature would automatically post a message, acknowledging the closure of an issue and thanking the contributors involved in the resolution.

### Use Case

This feature would enhance the user experience by adding a human touch to the automated processes within the project's issue tracking system. Upon issue closure, contributors and stakeholders would receive a warm acknowledgment, fostering a sense of appreciation and recognition for their efforts. Additionally, it would help maintain positive engagement and morale within the project community by celebrating milestones, such as issue resolutions, in a friendly and welcoming manner. Overall, this feature would contribute to a more inclusive and supportive environment for collaboration, encouraging continued participation and contribution from all project members.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Implementing a greeting message upon issue closure would add a touch of personalization and acknowledgment to the collaboration process within a project's issue tracker. This feature would automatically post a message, acknowledging the closure of an issue and thanking the contributors involved in the resolution.
> 
> ### Use Case
> This feature would enhance the user experience by adding a human touch to the automated processes within the project's issue tracking system. Upon issue closure, contributors and stakeholders would receive a warm acknowledgment, fostering a sense of appreciation and recognition for their efforts. Additionally, it would help maintain positive engagement and morale within the project community by celebrating milestones, such as issue resolutions, in a friendly and welcoming manner. Overall, this feature would contribute to a more inclusive and supportive environment for collaboration, encouraging continued participation and contribution from all project members.
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> Medium
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @thevijayshankersharma , Go for it
All the Best
