### ISSUE TITLE
[Feature Request]: Add a Preloader Component

### ISSUE THREAD

**Issue by pani2004** [Trisha-tech/OnlineBookSales#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The preloader will display a loading animation while the application is initializing or fetching data.

### Use Case

Loading animation

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by pani2004** [comment]
@Trisha-tech can I work on this?

**Comment by Sneha0019** [comment]
Hey, @Trisha-tech I can add this feature of preloader. Please assign it to me under an appropriate label

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> The preloader will display a loading animation while the application is initializing or fetching data.
> 
> ### Use Case
> Loading animation
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> Low
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Sneha0019 , Go for it
All the Best

**Comment by pani2004** [comment]
@Trisha-tech I think I had  opened this issue
