### ISSUE TITLE
[Feature Request]: Enable Dark Mode

### ISSUE THREAD

**Issue by GUNJESH843** [Trisha-tech/OnlineBookSales#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a dark mode option to the OnlineBookSales website to reduce eye strain during nighttime browsing. This mode will switch the website's color scheme to darker shades, making it easier on the eyes in low-light environments. Users should be able to toggle between light mode and dark mode from a switch in the website's header or settings.

### Use Case

Many users prefer to browse and read at night or in low-light conditions. A dark mode would make the website more comfortable to use during these times, potentially increasing user engagement and satisfaction.

### Benefits

Implementing a dark mode would:

1. Enhance user experience by providing a visually comfortable browsing option.
2. Attract users who prefer dark mode as a standard feature in modern applications.
3. Potentially reduce eye strain for users, contributing to better overall user health and satisfaction.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Anup2601** [comment]
I am GSSOC24 Contributor
Please assign me, I would like to work on it
@Trisha-tech

**Comment by GUNJESH843** [comment]
@Trisha-tech hey I would like to work on this issue.

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Add a dark mode option to the OnlineBookSales website to reduce eye strain during nighttime browsing. This mode will switch the website's color scheme to darker shades, making it easier on the eyes in low-light environments. Users should be able to toggle between light mode and dark mode from a switch in the website's header or settings.
> 
> ### Use Case
> Many users prefer to browse and read at night or in low-light conditions. A dark mode would make the website more comfortable to use during these times, potentially increasing user engagement and satisfaction.
> 
> ### Benefits
> Implementing a dark mode would:
> 
> 1. Enhance user experience by providing a visually comfortable browsing option.
> 2. Attract users who prefer dark mode as a standard feature in modern applications.
> 3. Potentially reduce eye strain for users, contributing to better overall user health and satisfaction.
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @GUNJESH843 , Go for it
All the Best
