### ISSUE TITLE
Wishlist frontend + Backend[Feature Request]: 

### ISSUE THREAD

**Issue by Sneha0019** [Trisha-tech/OnlineBookSales#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

So, when user visit the website and if he/she likes the book and wanted to buy afterwards then she can put the product into her wishlist.

### Use Case

when again user will visit to buy the product he/she can go into wishlist and buy the product instead of searching all over the website for the same product again

### Benefits

User convenience

### Add ScreenShots

![WISHLIST_FEATURE_ISSUE](https://github.com/Trisha-tech/OnlineBookSales/assets/112338459/c78b5dd5-9a6d-4d0e-8931-b58da9f920bd)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Sneha0019** [comment]
Hello, @Trisha-tech please assign me this issue under an appropriate label

**Comment by Trisha-tech** [comment]
> Hello, @Trisha-tech please assign me this issue under an appropriate label

Hello @Sneha0019 , Go for it
All the Best
