### ISSUE TITLE
Design Navigation bar UI using React, Tailwindcss 

### ISSUE THREAD

**Issue by ArtiGaund** [Trisha-tech/OnlineBookSales#18]
Want to design nav bar with items
1) Home
2) Book store
3) Profile
4) Order 
5) Sign-in/Sign-up

**Comment by Trisha-tech** [comment]
> Want to design nav bar with items
> 
> 1. Home
> 2. Book store
> 3. Profile
> 4. Order
> 5. Sign-in/Sign-up

Go for it @ArtiGaund 
All the Best

**Comment by Aadityagoel15** [comment]
hey @Trisha-tech 
Can you also assign this issue to me under GSSOC 2024 please. I would like to contribute to this too

**Comment by CharviPalem** [comment]
@Trisha-tech
I would like to contribute to this too....Can you please assign me this issue under GSSOC 2024 please.

**Comment by ArtiGaund** [comment]
![Screenshot (259)](https://github.com/Trisha-tech/OnlineBookSales/assets/38074085/63c16650-2b2b-4c72-92d9-f4a22dac63a3)
I
![Screenshot (260)](https://github.com/Trisha-tech/OnlineBookSales/assets/38074085/6af47e0c-ac9a-498a-b921-c009b1349640)
@Trisha-tech is this navigation bar ok? Is anything else you want in it?

**Comment by Trisha-tech** [comment]
> ![Screenshot (259)](https://private-user-images.githubusercontent.com/38074085/329761179-63c16650-2b2b-4c72-92d9-f4a22dac63a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTEwOTIsIm5iZiI6MTcxNTQxMDc5MiwicGF0aCI6Ii8zODA3NDA4NS8zMjk3NjExNzktNjNjMTY2NTAtMmIyYi00YzcyLTkyZDktZjRhMjJkYWM2M2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA2NTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZDNhNGNjMjc3NTBlZWUyZjk4MmRhNzNiZDIzZDU3MTE2YTA5MDA0MGM2YWJjN2NlYTQ2YzY5YzYxMjRmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uj2-uk1CIpw-KuPcyfpe5F-jUcllGeSBjTnHbr-8psE) I ![Screenshot (260)](https://private-user-images.githubusercontent.com/38074085/329761187-6af47e0c-ac9a-498a-b921-c009b1349640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTEwOTIsIm5iZiI6MTcxNTQxMDc5MiwicGF0aCI6Ii8zODA3NDA4NS8zMjk3NjExODctNmFmNDdlMGMtYWM5YS00OThhLWI5MjEtYzAwOWIxMzQ5NjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA2NTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOGVmNzM0MmM2NTI3YWMzNTBjMTc4MzAxZTNjY2JlN2JjMzEwNDM1ZGZhYmFlNGI4ODczMjZkMjE4MGVmNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5w-hqOjoRuqw-r8z6uBVYy4apfRvuNrccsDeUQI_jq4) @Trisha-tech is this navigation bar ok? Is anything else you want in it?

Looks good @ArtiGaund 
Make the PR

**Comment by ArtiGaund** [comment]
ok

**Comment by Hardikchandra** [comment]
want to add.
1. about us option in the navbar.
2. cart icon.
3. notification bar above navbar for promotion/displaying important messages.

**Comment by ArtiGaund** [comment]
@Trisha-tech  forgot to add a search bar in the navigation bar. As I have created the controller for searchProduct, should I create a search bar as well for it?

**Comment by ArtiGaund** [comment]
Navbar done
