### ISSUE TITLE
Add a Featured Author Section

### ISSUE THREAD

**Issue by arunimaChintu** [Trisha-tech/OnlineBookSales#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "Featured Author" section is a new addition to our homepage designed to highlight notable authors and their works. This section aims to provide our users with an in-depth look at authors who have made significant contributions to the literary world. Here's a detailed description of its features and functionalities:

### Use Case

Book Enthusiasts: Discover and explore featured authors, their biographies, and notable works in one place, enhancing their reading choices.

Educators: Access curated author profiles and book recommendations to enrich classroom discussions and inspire students.

Publishers: Showcase authors and promote their books, driving visibility and sales through targeted marketing campaigns.

### Benefits

The "Featured Author" section provides several benefits:

Enhanced Discovery: Readers can discover new authors and explore their works conveniently.

Educational Value: Educators gain access to curated content for enriching learning experiences.

Promotional Platform: Authors and publishers benefit from increased visibility and promotion of their books.

Engagement: Users enjoy a seamless and engaging browsing experience, fostering deeper connections with literary figures.

### Add ScreenShots

<img width="1405" alt="Screenshot 2024-06-23 at 1 35 25 PM" src="https://github.com/Trisha-tech/OnlineBookSales/assets/99474881/4e2fc2c0-25d5-43e1-be0e-2c050dbd19e2">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by arunimaChintu** [comment]
@Trisha-tech Please assign me this issue!

**Comment by arunimaChintu** [comment]
I am not able to upload it @Trisha-tech 
<img width="307" alt="Screenshot 2024-06-23 at 1 50 44 PM" src="https://github.com/Trisha-tech/OnlineBookSales/assets/99474881/7c2b5bef-61aa-4551-8517-33cae373e13b">

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> The "Featured Author" section is a new addition to our homepage designed to highlight notable authors and their works. This section aims to provide our users with an in-depth look at authors who have made significant contributions to the literary world. Here's a detailed description of its features and functionalities:
> 
> ### Use Case
> Book Enthusiasts: Discover and explore featured authors, their biographies, and notable works in one place, enhancing their reading choices.
> 
> Educators: Access curated author profiles and book recommendations to enrich classroom discussions and inspire students.
> 
> Publishers: Showcase authors and promote their books, driving visibility and sales through targeted marketing campaigns.
> 
> ### Benefits
> The "Featured Author" section provides several benefits:
> 
> Enhanced Discovery: Readers can discover new authors and explore their works conveniently.
> 
> Educational Value: Educators gain access to curated content for enriching learning experiences.
> 
> Promotional Platform: Authors and publishers benefit from increased visibility and promotion of their books.
> 
> Engagement: Users enjoy a seamless and engaging browsing experience, fostering deeper connections with literary figures.
> 
> ### Add ScreenShots
> <img alt="Screenshot 2024-06-23 at 1 35 25 PM" width="1405" src="https://private-user-images.githubusercontent.com/99474881/342050961-4e2fc2c0-25d5-43e1-be0e-2c050dbd19e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzczMTIsIm5iZiI6MTcxOTEzNzAxMiwicGF0aCI6Ii85OTQ3NDg4MS8zNDIwNTA5NjEtNGUyZmMyYzAtMjVkNS00M2UxLWJlMGUtMmMwNTBkYmQxOWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEwMDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZmM0YjFiMjAwZTBlZDk2NWViNmE4NGE0ZTkwOTY1MzdkMGY4ZDNmOWZlZGQ3NmFhMGI2MTVhOTc0ZjA5MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-8bZpkjpnTj_eFem39oFbDSGqqYVzijb2RDbmXUdVN8">
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @arunimaChintu , Go for it
All the Best
