### ISSUE TITLE
[Bug]: Website not working properly

### ISSUE THREAD

**Issue by UtkarshBirla28** [Trisha-tech/OnlineBookSales#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 Website not working properly there is no UI and taking time to load 

### Expected behavior

 Website not working properly there is no UI and taking time to load 

### Add ScreenShots

![Screenshot (94)](https://github.com/Trisha-tech/OnlineBookSales/assets/96072228/058e3da5-ef66-4623-94e6-6370884bcd92)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> Website not working properly there is no UI and taking time to load
> 
> ### Expected behavior
> Website not working properly there is no UI and taking time to load
> 
> ### Add ScreenShots
> ![Screenshot (94)](https://private-user-images.githubusercontent.com/96072228/342847056-058e3da5-ef66-4623-94e6-6370884bcd92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzODM0OTQsIm5iZiI6MTcxOTM4MzE5NCwicGF0aCI6Ii85NjA3MjIyOC8zNDI4NDcwNTYtMDU4ZTNkYTUtZWY2Ni00NjIzLTk0ZTYtNjM3MDg4NGJjZDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA2MjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NGEyM2FjMzMzNzRkZGY2YjY3MzVmMzc4MDIzYWY0YzRiNzJjNGUyM2M2OTMxYTE5ZGVkMmI5NjQyMWI5OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RhEC3XGh3hXPzuB4ddylBKawZ7lwmGx8X7eN3JLGalc)
> 
> ### On which device are you experiencing this bug?
> Chrome
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @UtkarshBirla28 , Go to client folder and first run "npm install" and then run "npm start"
