### ISSUE TITLE
[Feature Request]: Add a " SEARCH BAR FOR BOOKS"

### ISSUE THREAD

**Issue by arunimaChintu** [Trisha-tech/OnlineBookSales#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This code adds a search bar component to the Home page. The handleSearch function currently logs the search query to the console; you can implement the actual search logic as needed.

### Use Case

This code adds a search bar component to the Home page. The handleSearch function currently logs the search query to the console; you can implement the actual search logic as needed.

### Benefits

This code adds a search bar component to the Home page. The handleSearch function currently logs the search query to the console; you can implement the actual search logic as needed.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> This code adds a search bar component to the Home page. The handleSearch function currently logs the search query to the console; you can implement the actual search logic as needed.
> 
> ### Use Case
> This code adds a search bar component to the Home page. The handleSearch function currently logs the search query to the console; you can implement the actual search logic as needed.
> 
> ### Benefits
> This code adds a search bar component to the Home page. The handleSearch function currently logs the search query to the console; you can implement the actual search logic as needed.
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @arunimaChintu , Go for it
All the Best
