### ISSUE TITLE
Want to add logout controller in customerController

### ISSUE THREAD

**Issue by cwatr** [Trisha-tech/OnlineBookSales#19]
I want to create a logout controller by changing refresh tokens, but before that, I would have to use access and refresh tokens in login and signup authentication. Can you please assign it to me?

**Comment by rawani123** [comment]
can you assign this to me as i work more on mern stack so i can your backend with the frontend

**Comment by Trisha-tech** [comment]
> I want to create a logout controller by changing refresh tokens, but before that, I would have to use access and refresh tokens in login and signup authentication. Can you please assign it to me?

Hello @cwatr , Go for it
All the best
