### ISSUE TITLE
[Feature Request]: **INTRODUCING REAL-TIME ORDER TRACKING: SEAMLESSLY MONITOR YOUR ORDER STATUS AND DELIVERY UPDATES**

### ISSUE THREAD

**Issue by arunimaChintu** [Trisha-tech/OnlineBookSales#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Key Features Added:
Order ID Input: Allows users to input their order ID.
Track Order Button: Triggers the fetch call to get order status.
Order Status Display: Shows the order status and expected delivery date.

### Use Case

Let's add an "Order Tracking" feature to the Orders component. This feature will include an input field for the user to enter an order ID, a button to trigger the search, and a section to display the order status.

### Benefits

This feature will include an input field for the user to enter an order ID, a button to trigger the search, and a section to display the order status.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Key Features Added: Order ID Input: Allows users to input their order ID. Track Order Button: Triggers the fetch call to get order status. Order Status Display: Shows the order status and expected delivery date.
> 
> ### Use Case
> Let's add an "Order Tracking" feature to the Orders component. This feature will include an input field for the user to enter an order ID, a button to trigger the search, and a section to display the order status.
> 
> ### Benefits
> This feature will include an input field for the user to enter an order ID, a button to trigger the search, and a section to display the order status.
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @arunimaChintu , Go for it 
All The Best

**Comment by arunimaChintu** [comment]
@Trisha-tech Please assign me this issue
