### ISSUE TITLE
[Feature Request]: Create CART page  both [ FRONTEND + BACKEND]

### ISSUE THREAD

**Issue by arunimaChintu** [Trisha-tech/OnlineBookSales#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Key Features
Frontend

Display cart items with options to add or remove items.
Display total cart value.
Loading spinner during API calls.
Backend

Fetch cart data.
Add item to cart.
Remove item from cart.

### Use Case

Key Features
Frontend

Display cart items with options to add or remove items.
Display total cart value.
Loading spinner during API calls.
Backend

Fetch cart data.
Add item to cart.
Remove item from cart.

### Benefits

Key Features
Frontend

Display cart items with options to add or remove items.
Display total cart value.
Loading spinner during API calls.
Backend

Fetch cart data.
Add item to cart.
Remove item from cart.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by arunimaChintu** [comment]
@Trisha-tech CART page [ Both frontend + backend]

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Key Features Frontend
> 
> Display cart items with options to add or remove items. Display total cart value. Loading spinner during API calls. Backend
> 
> Fetch cart data. Add item to cart. Remove item from cart.
> 
> ### Use Case
> Key Features Frontend
> 
> Display cart items with options to add or remove items. Display total cart value. Loading spinner during API calls. Backend
> 
> Fetch cart data. Add item to cart. Remove item from cart.
> 
> ### Benefits
> Key Features Frontend
> 
> Display cart items with options to add or remove items. Display total cart value. Loading spinner during API calls. Backend
> 
> Fetch cart data. Add item to cart. Remove item from cart.
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @arunimaChintu , Go for it
All the Best
