### ISSUE TITLE
[Feature Request]: Access Token & refresh Token

### ISSUE THREAD

**Issue by Vinaysohaliya** [Trisha-tech/OnlineBookSales#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add an access token and refresh token for smooth auth experiences kindly assign me this under GSSOC 24 @Trisha-tech.

### Use Case

Improved Security: Access tokens and refresh tokens help in maintaining secure communication between the client and server by ensuring that only authenticated users can access protected resources. This reduces the risk of unauthorized access.

Seamless User Experience: By using tokens, you can implement automatic token refreshing without requiring users to log in repeatedly. This creates a more seamless and user-friendly experience.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> I want to add an access token and refresh token for smooth auth experiences kindly assign me this under GSSOC 24 @Trisha-tech.
> 
> ### Use Case
> Improved Security: Access tokens and refresh tokens help in maintaining secure communication between the client and server by ensuring that only authenticated users can access protected resources. This reduces the risk of unauthorized access.
> 
> Seamless User Experience: By using tokens, you can implement automatic token refreshing without requiring users to log in repeatedly. This creates a more seamless and user-friendly experience.
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Vinaysohaliya , Go for It
All the Best
