### ISSUE TITLE
Missing Code of Conduct File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [Trisha-tech/OnlineBookSales#20]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Please  assign me this issue.

**Comment by Trisha-tech** [comment]
> Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.
> 
> Please assign me this issue.

Hello @suhanipaliwal , Go for it
All the Best

**Comment by AmrutaZagade** [comment]
Hey @Trisha-tech can you please assign me this issue.
