### ISSUE TITLE
[Feature Request]: Add a HOME section in the Navbar(cause once we shift we another page, theres no button to go back to the home page)

### ISSUE THREAD

**Issue by arunimaChintu** [Trisha-tech/OnlineBookSales#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a HOME section in the Navbar(cause once we shift we another page, theres no button to go back to the home page)

### Use Case

Add a HOME section in the Navbar(cause once we shift we another page, theres no button to go back to the home page)

### Benefits

Add a HOME section in the Navbar(cause once we shift we another page, theres no button to go back to the home page)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Add a HOME section in the Navbar(cause once we shift we another page, theres no button to go back to the home page)
> 
> ### Use Case
> Add a HOME section in the Navbar(cause once we shift we another page, theres no button to go back to the home page)
> 
> ### Benefits
> Add a HOME section in the Navbar(cause once we shift we another page, theres no button to go back to the home page)
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @arunimaChintu , Go for it
All the best
