### ISSUE TITLE
[Feature Request]: Both Make and Add a Favicon logo for the website

### ISSUE THREAD

**Issue by arunimaChintu** [Trisha-tech/OnlineBookSales#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Both Make and Add a Favicon logo for the website

### Use Case

Both Make and Add a Favicon logo for the website

### Benefits

Both Make and Add a Favicon logo for the website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Both Make and Add a Favicon logo for the website
> 
> ### Use Case
> Both Make and Add a Favicon logo for the website
> 
> ### Benefits
> Both Make and Add a Favicon logo for the website
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @arunimaChintu , Go for it
All the Best
