### ISSUE TITLE
[Feature Request]: Adding docker compose

### ISSUE THREAD

**Issue by Ratangulati** [Trisha-tech/OnlineBookSales#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

docker compose allows you to define and manage multi-container Docker applications. It also make it easy to work with and deploy the entire application stack.

### Use Case

It runs the container in one code and some of it valuable features
Multi-Container Deployment
Easy Management
Isolation

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> docker compose allows you to define and manage multi-container Docker applications. It also make it easy to work with and deploy the entire application stack.
> 
> ### Use Case
> It runs the container in one code and some of it valuable features Multi-Container Deployment Easy Management Isolation
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Ratangulati , Go for it
All the Best

**Comment by agarwalhimanshugaya** [comment]
@Trisha-tech if no one doing on this issue kindly assign to me

**Comment by vigneshwarap** [comment]
Hi @Trisha-tech 
I would like to work on this feature to dockerize the application. If you are ok please assign to me.
