### ISSUE TITLE
[Bug]: FIX THESE bugs erros  in ALL these 4 pages

### ISSUE THREAD

**Issue by arunimaChintu** [Trisha-tech/OnlineBookSales#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

THis is the errors coming... I want to solve this

### Expected behavior

This corrects all the errors in the website...

### Add ScreenShots

<img width="1366" alt="Screenshot 2024-08-03 at 3 19 25 PM" src="https://github.com/user-attachments/assets/6f728b7e-3056-4c90-b075-074c587cba5e">

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by arunimaChintu** [comment]
![Uploading Screenshot 2024-08-03 at 3.19.25 PM.png…]()

**Comment by arunimaChintu** [comment]
@Trisha-tech I have worked on these errors on all these 4 pages... And all the errors are gone now... Please assign me this issue... I will Push my code

**Comment by arunimaChintu** [comment]
@Trisha-tech Please assign me this issue

**Comment by Trisha-tech** [comment]
> @Trisha-tech I have worked on these errors on all these 4 pages... And all the errors are gone now... Please assign me this issue... I will Push my code

Hello @arunimaChintu , Go for it
All the Best
