### ISSUE TITLE
[Bug]: Dark mode issue at login and signup page

### ISSUE THREAD

**Issue by Sourabh782** [Trisha-tech/OnlineBookSales#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The text content on login and signup page is not readable in dark mode

### Expected behavior

there should be proper visiblity to all component in dark mode

### Add ScreenShots

![Screenshot 2024-08-05 190358](https://github.com/user-attachments/assets/ae35f741-bf79-4c45-a0ce-7df246573ed4)
![Screenshot 2024-08-05 190253](https://github.com/user-attachments/assets/dffe7428-23cc-4c41-8cc6-3d35c4ba5a0e)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> The text content on login and signup page is not readable in dark mode
> 
> ### Expected behavior
> there should be proper visiblity to all component in dark mode
> 
> ### Add ScreenShots
> ![Screenshot 2024-08-05 190358](https://private-user-images.githubusercontent.com/103349890/355122630-ae35f741-bf79-4c45-a0ce-7df246573ed4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Nzk2NjEsIm5iZiI6MTcyMjg3OTM2MSwicGF0aCI6Ii8xMDMzNDk4OTAvMzU1MTIyNjMwLWFlMzVmNzQxLWJmNzktNGM0NS1hMGNlLTdkZjI0NjU3M2VkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxNzM2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDdkZGY4NjUyNjg5Yjg1MzE3Y2FmZjJiYWMxZWQ0MzA1NWYwNzQzZmQyZjM4MjI1ZmFjMTM5MzA0YTdiN2E5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._mC2yAxUTJAB0P5Lp3Fei1qIc_ICygx63Uyu7ppGEts) ![Screenshot 2024-08-05 190253](https://private-user-images.githubusercontent.com/103349890/355122647-dffe7428-23cc-4c41-8cc6-3d35c4ba5a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Nzk2NjEsIm5iZiI6MTcyMjg3OTM2MSwicGF0aCI6Ii8xMDMzNDk4OTAvMzU1MTIyNjQ3LWRmZmU3NDI4LTIzY2MtNGM0MS04Y2M2LTNkMzVjNGJhNWEwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxNzM2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDc1YjlhN2MxNDljNWM5YTk1MGQwMjA1ZGRlM2UwZTdjZmFkMGE2YTBjMmRjYzQ4NmYwNDQ5MWY5ZjgzZDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ofsY26UZ-cdFT7LMEgtD1yKh5HviP1KFiBrs6utzUnA)
> 
> ### On which device are you experiencing this bug?
> Chrome
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Sourabh782 , Go for it
All the Best

**Comment by Sourabh782** [comment]
Thanks @Trisha-tech, working on it 👍

**Comment by Sourabh782** [comment]
@Trisha-tech Kindly check the PR
