### ISSUE TITLE
Add A Preloader Matching to Website Theme i.e. Books

### ISSUE THREAD

**Issue by MastanSayyad** [Trisha-tech/OnlineBookSales#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Trisha-tech 

 As the theme of the website is BOOKS I would like to design a preloader for the website

These are my previous works for your reference:

https://github.com/user-attachments/assets/59e674d7-88cb-4bca-9765-291e99467f68

https://github.com/user-attachments/assets/c33f2566-4b43-47d3-88d2-d48226da13df

Similary I will try to create a preloader something related to Books

### Use Case

N/A

### Benefits

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Hey @Trisha-tech
> 
> As the theme of the website is BOOKS I would like to design a preloader for the website
> 
> These are my previous works for your reference:
> 
>  06.08.2024_01.02.27_REC.mp4 
>  06.08.2024_04.07.42_REC.mp4 
> Similary I will try to create a preloader something related to Books
> 
> ### Use Case
> N/A
> 
> ### Benefits
> N/A
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @MastanSayyad , Go for it
All the Best
