### ISSUE TITLE
[Feature Request]: Add Legal Section and Copyright section with dynamic date functionality

### ISSUE THREAD

**Issue by MastanSayyad** [Trisha-tech/OnlineBookSales#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Trisha-tech I would like to add a legal section to the footer to ensure professionalism
and  a `Copyright` section with `dynamic date functionality` which will update by `yearly`!

![image](https://github.com/user-attachments/assets/446ac740-4095-46e8-bddf-17a9377bedab)

I will also create their respective pages in the next issues. as gssoc is near to it's end I will complete it asap before the event ends!

Additionally, I would like to Remove the unnecessary padding of the applications body.

![image](https://github.com/user-attachments/assets/62a82488-d529-49e1-826e-e62cbe5f4b21)

### Use Case

Ensure professionalism and user clarification

### Benefits

N/A

### Add ScreenShots

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Hey @Trisha-tech I would like to add a legal section to the footer to ensure professionalism and a `Copyright` section with `dynamic date functionality` which will update by `yearly`!
> 
> ![image](https://private-user-images.githubusercontent.com/101971980/355649508-446ac740-4095-46e8-bddf-17a9377bedab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjA4NzgsIm5iZiI6MTcyMzAyMDU3OCwicGF0aCI6Ii8xMDE5NzE5ODAvMzU1NjQ5NTA4LTQ0NmFjNzQwLTQwOTUtNDZlOC1iZGRmLTE3YTkzNzdiZWRhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwODQ5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2UzZjMxYzI3MDM4NzZmYmJhY2RkY2E0NTRjNWEyZTQ5NzUxZjQ2ZGVmYmQwMWIzMjg1ZWYxNzhmMmRjY2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fkCJCMZMH11l3QuDD_0i4BF0qpzoxCHousI86YlV_Dw)
> 
> I will also create their respective pages in the next issues. as gssoc is near to it's end I will complete it asap before the event ends!
> 
> Additionally, I would like to Remove the unnecessary padding of the applications body.
> 
> ![image](https://private-user-images.githubusercontent.com/101971980/355648773-62a82488-d529-49e1-826e-e62cbe5f4b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjA4NzgsIm5iZiI6MTcyMzAyMDU3OCwicGF0aCI6Ii8xMDE5NzE5ODAvMzU1NjQ4NzczLTYyYTgyNDg4LWQ1MjktNDllMS04MjZlLWU2MmNiZTVmNGIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwODQ5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODRkNzRjM2E1MDFkNTVkNDhmNTIxNmRjYzk0ZWIxODJhMWYwZDRlNWU1MTQ3NjczNWZhNzZiMmIxZjM1NTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W4MrcnmtCe6T7Rsf6_aYWA4HIPz9vKuz66v0AZ3mU6I)
> 
> ### Use Case
> Ensure professionalism and user clarification
> 
> ### Benefits
> N/A
> 
> ### Add ScreenShots
> N/A
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @MastanSayyad , Go for it
All the Best
