### ISSUE TITLE
[Feature Request]: Create and make 404 error page 

### ISSUE THREAD

**Issue by arunimaChintu** [Trisha-tech/OnlineBookSales#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Create and make 404 error page 

### Use Case

Create and make 404 error page 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Create and make 404 error page
> 
> ### Use Case
> Create and make 404 error page
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @arunimaChintu , Go for it
All the Best

**Comment by Sourabh782** [comment]
@Trisha-tech can i work on this?

**Comment by Trisha-tech** [comment]
> @Trisha-tech can i work on this?

Hello @Sourabh782, Go for it
All the Best
