### ISSUE TITLE
[Bug]:  Order section display issue

### ISSUE THREAD

**Issue by Sourabh782** [Trisha-tech/OnlineBookSales#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In order section the navbar and footer are joined together ( If the orders are empty ).
 

### Expected behavior

If orders are empty then also there should be a proper spacing between navbar and footer of the website

### Add ScreenShots

![Screenshot 2024-08-07 101239](https://github.com/user-attachments/assets/2757edb5-7cf9-40a0-bf2d-4e129fcbbeed)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> In order section the navbar and footer are joined together ( If the orders are empty ).
> 
> ### Expected behavior
> If orders are empty then also there should be a proper spacing between navbar and footer of the website
> 
> ### Add ScreenShots
> ![Screenshot 2024-08-07 101239](https://private-user-images.githubusercontent.com/103349890/355677612-2757edb5-7cf9-40a0-bf2d-4e129fcbbeed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjA4NzQsIm5iZiI6MTcyMzAyMDU3NCwicGF0aCI6Ii8xMDMzNDk4OTAvMzU1Njc3NjEyLTI3NTdlZGI1LTdjZjktNDBhMC1iZjJkLTRlMTI5ZmNiYmVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwODQ5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjNhODcwNzc1NDgxYmIzOGEyNDhkZGQ2ZjEyMDFiNzRiMGI3MzI2NzkwOWUwZjJkNzQyYmUwZGY3NzgzOGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rjX9NC_6FQ1ihApFzzNcOswaDIQO9UkAWvHnoVcu-K0)
> 
> ### On which device are you experiencing this bug?
> Chrome
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Sourabh782 , Go for it
All the Best
