### ISSUE TITLE
[Feature Request]: Properly Implementing the dark mode for whole website

### ISSUE THREAD

**Issue by Sourabh782** [Trisha-tech/OnlineBookSales#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently the dark mode is not properly applied on whole website, making is not look good in dark mode

### Use Case

The dark mode should be properly applied throughout the site

### Benefits

Improves readablity and reduces eye strain while browsing in dim lights.
also now a days people prefer dark mode

### Add ScreenShots

![Screenshot 2024-08-07 101834](https://github.com/user-attachments/assets/daf48e75-0839-496b-84d6-04c0a9e578d8)
![Screenshot 2024-08-07 101822](https://github.com/user-attachments/assets/95f1fa9c-eda5-4527-9705-2a12ef6993cf)
![Screenshot 2024-08-07 101811](https://github.com/user-attachments/assets/eb7a40eb-de29-4192-a8f5-b2fe070b9198)
![Screenshot 2024-08-07 101804](https://github.com/user-attachments/assets/3d4d6fb6-a35f-45db-8831-8536903ed11f)
![Screenshot 2024-08-07 101756](https://github.com/user-attachments/assets/91e08dc3-9b91-4dc4-b7f6-7ccf467d24c3)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Currently the dark mode is not properly applied on whole website, making is not look good in dark mode
> 
> ### Use Case
> The dark mode should be properly applied throughout the site
> 
> ### Benefits
> Improves readablity and reduces eye strain while browsing in dim lights. also now a days people prefer dark mode
> 
> ### Add ScreenShots
> ![Screenshot 2024-08-07 101834](https://private-user-images.githubusercontent.com/103349890/355678280-daf48e75-0839-496b-84d6-04c0a9e578d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjA4NzIsIm5iZiI6MTcyMzAyMDU3MiwicGF0aCI6Ii8xMDMzNDk4OTAvMzU1Njc4MjgwLWRhZjQ4ZTc1LTA4MzktNDk2Yi04NGQ2LTA0YzBhOWU1NzhkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwODQ5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTE1ZmFhNDUzMmRlODViNzRkNWVlNTE1YmIxZTA3NDE2NGIxZTM1Y2FmNTA3N2NmOTc4ZGZjYzZjODRjOGI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nr1cMkXkxS17OuEh8en3JOoRYjjfxs-qWs_M2hToMT8) ![Screenshot 2024-08-07 101822](https://private-user-images.githubusercontent.com/103349890/355678292-95f1fa9c-eda5-4527-9705-2a12ef6993cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjA4NzIsIm5iZiI6MTcyMzAyMDU3MiwicGF0aCI6Ii8xMDMzNDk4OTAvMzU1Njc4MjkyLTk1ZjFmYTljLWVkYTUtNDUyNy05NzA1LTJhMTJlZjY5OTNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwODQ5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDBiOGMwMDE1NmM2ZWVhYzE1NTA4Mjc5NTU0YzJhNWQ3NGVhMzBmMjliNTk0NWZkODUxZTY3NDZkNjY5OGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tmyNII2CpwPc64f--D8DHPRG66BYSJURZFWBY6q0CZY) ![Screenshot 2024-08-07 101811](https://private-user-images.githubusercontent.com/103349890/355678294-eb7a40eb-de29-4192-a8f5-b2fe070b9198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjA4NzIsIm5iZiI6MTcyMzAyMDU3MiwicGF0aCI6Ii8xMDMzNDk4OTAvMzU1Njc4Mjk0LWViN2E0MGViLWRlMjktNDE5Mi1hOGY1LWIyZmUwNzBiOTE5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwODQ5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWZiYzY4NGJiNWE4Nzg5MDhiOGRiZTI3NDc3YjcyNmNkMzIyNTczMTZhNjhlYTc1NzY0MjMxYzM2YmJkMDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JMsOeNXzleSwmRyzRo385vFx4I07LJvghA2ET4VhroY) ![Screenshot 2024-08-07 101804](https://private-user-images.githubusercontent.com/103349890/355678296-3d4d6fb6-a35f-45db-8831-8536903ed11f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjA4NzIsIm5iZiI6MTcyMzAyMDU3MiwicGF0aCI6Ii8xMDMzNDk4OTAvMzU1Njc4Mjk2LTNkNGQ2ZmI2LWEzNWYtNDVkYi04ODMxLTg1MzY5MDNlZDExZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwODQ5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTVmOTczNThlNGMyNDk0NTQxY2E3YmJiODA0OWI1ZjE4NjViZGE4NjIxMDc2OWQzN2M3YWI4NjU5ZDBiZGViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v3RpuEgU8NRmwffV7Lky0JNG-JiUF7GJ2oZnbGcAOTU) ![Screenshot 2024-08-07 101756](https://private-user-images.githubusercontent.com/103349890/355678299-91e08dc3-9b91-4dc4-b7f6-7ccf467d24c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjA4NzIsIm5iZiI6MTcyMzAyMDU3MiwicGF0aCI6Ii8xMDMzNDk4OTAvMzU1Njc4Mjk5LTkxZTA4ZGMzLTliOTEtNGRjNC1iN2Y2LTdjY2Y0NjdkMjRjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwODQ5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2E5OTZhMTFjYzZhYjhkZDY4NzEzYTg4NWVhYTM5YmRmNGVkODM1ZmJhMzMyMzI1YjJlMmI5YmQ3MGYzNDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ovQslaDmVUme-hPDUK0i6RMMeudho0ggqsJbUzqVbrI)
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Sourabh782 , Go for it
All the Best

**Comment by Sourabh782** [comment]
@Trisha-tech sure, working on it :)
