### ISSUE TITLE
Add the Cursor Trial Effect to the Website

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Trisha-tech/OnlineBookSales#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Trisha-tech 

I would like to add the cursor trail effect to the website 

like this 

https://github.com/user-attachments/assets/5262d892-ebbb-4b2b-821f-f41dc675db55

### Use Case

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Hey @Trisha-tech
> 
> I would like to add the cursor trail effect to the website
> 
> like this
> 
>  trail.1.mp4 
> ### Use Case
> N/A
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @RadhikaMalpani1702 , Go for it
All the Best
