### ISSUE TITLE
Checkout Frontend

### ISSUE THREAD

**Issue by R1MO9** [Trisha-tech/OnlineBookSales#23]
@Trisha-tech I want to make a frontend checkout page using react for this  #22 issue

**Comment by Trisha-tech** [comment]
> i want to make a frontend checkout page using react for this #22 issue

Hello @R1MO9 , Go for it
All the best

**Comment by RakshitaJain2126** [comment]
Hello,I am a frontend web developer.I want to work on this too.Can you assign to me also?

**Comment by Manaswini123456** [comment]
Hello, I am a full stack developer with the required tech stack, kindly assign me with this issue so that I can provide my insights and solutions.

**Comment by AmrutaZagade** [comment]
Hey @Trisha-tech I would like to work on this issue.
