### ISSUE TITLE
Design A New Logo and A Fevicon for The Website

### ISSUE THREAD

**Issue by MastanSayyad** [Trisha-tech/OnlineBookSales#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Trisha-tech 

I would like to design a new logo and a Favicon for the website As I believe the current ones are not too attractive and engaging

### **Current Favicon:**
![image](https://github.com/user-attachments/assets/1719f7b4-777b-4055-8167-b0d3bdbc7c9e)

### **Current Logo:**
![image](https://github.com/user-attachments/assets/6a3bd98f-a37b-4704-aba9-d57f7ff0db19)

### Use Case

I have designed a great logo for this amazing website that matches its design theme and will look more attractive!!

### I have Designed This **Favicon**  For Your Website 

![image](https://github.com/user-attachments/assets/f8ce6767-a8c9-4130-a0ca-7b019b72c8c8)

### And This is the **Logo**

![image](https://github.com/user-attachments/assets/938e797d-e316-4a1e-969c-f5a36e8c262f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Hey @Trisha-tech
> 
> I would like to design a new logo and a Favicon for the website As I believe the current ones are not too attractive and engaging
> 
> ### **Current Favicon:**
> ![image](https://private-user-images.githubusercontent.com/101971980/356054757-1719f7b4-777b-4055-8167-b0d3bdbc7c9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDY1NzYsIm5iZiI6MTcyMzEwNjI3NiwicGF0aCI6Ii8xMDE5NzE5ODAvMzU2MDU0NzU3LTE3MTlmN2I0LTc3N2ItNDA1NS04MTY3LWIwZDNiZGJjN2M5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwODM3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTI0NmM3NTU1OGE4ZWQ2YzM0Yjk2ZTkxZjEzMWQ3NGJhMTdlM2I4ZjlkMjcyMThlOGQzZTNiOTJkY2ZiNzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VKCUFHDTtp5C3QKmSNHS9TOtG1_HcXw3CDUYGl2MHkg)
> 
> ### **Current Logo:**
> ![image](https://private-user-images.githubusercontent.com/101971980/356055109-6a3bd98f-a37b-4704-aba9-d57f7ff0db19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDY1NzYsIm5iZiI6MTcyMzEwNjI3NiwicGF0aCI6Ii8xMDE5NzE5ODAvMzU2MDU1MTA5LTZhM2JkOThmLWEzN2ItNDcwNC1hYmE5LWQ1N2Y3ZmYwZGIxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwODM3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTgxMGJmYmU2NGM5NzdmYWY4ODNmNDg4MTY4NTRmNTg5MWI3ZmZhNDQ2ZWM4MTM3MzU2Y2MxOGZhNDg0NDk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.--p_6HfvPpT92Xxe5JpL-ilJUTcqrrp2cna3Jq7sflw)
> 
> ### Use Case
> I have designed a great logo for this amazing website that matches its design theme and will look more attractive!!
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> ### I have Designed This **Favicon** For Your Website
> ![image](https://private-user-images.githubusercontent.com/101971980/356059385-f8ce6767-a8c9-4130-a0ca-7b019b72c8c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDY1NzYsIm5iZiI6MTcyMzEwNjI3NiwicGF0aCI6Ii8xMDE5NzE5ODAvMzU2MDU5Mzg1LWY4Y2U2NzY3LWE4YzktNDEzMC1hMGNhLTdiMDE5YjcyYzhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwODM3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2JiY2NhMjg2MzYwNGNmMzIwMmFlZGI3YjhmZDZhNTcyN2IwYTU2MjE0M2ZhZmQ1ZjBkMzU1ZTQxZmU0Yzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wLcVSjmX69NcISWMmkg3dQjW9b4zG3L69u0kmR-igBM)
> 
> ### And This is the **Logo**
> ![image](https://private-user-images.githubusercontent.com/101971980/356059221-938e797d-e316-4a1e-969c-f5a36e8c262f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDY1NzYsIm5iZiI6MTcyMzEwNjI3NiwicGF0aCI6Ii8xMDE5NzE5ODAvMzU2MDU5MjIxLTkzOGU3OTdkLWUzMTYtNGExZS05NjljLWY1YTM2ZThjMjYyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwODM3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTE2OGY4MzhiNzRmNzQ0ZTcyN2MyY2NlZTllMDFkNDE2YjdjMmFmMTcyY2Q1MjM0OTVjOGYxNTdhYzcwODkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9HXP-8QUn_pOHns92KIaQ8DUJGYVeMiHzV9_ADHdVuU)
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @MastanSayyad , Go for it
All the Best
