### ISSUE TITLE
Create Terms and Conditions Page For the Website

### ISSUE THREAD

**Issue by MastanSayyad** [Trisha-tech/OnlineBookSales#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Trisha-tech 

I would like to create Terms and Conditions Page for the website 

![image](https://github.com/user-attachments/assets/9cdcdacf-42f1-465f-acdc-8b249ed68f9b)

### Use Case

N/A

### Benefits

N/A

### Add ScreenShots

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Hey @Trisha-tech
> 
> I would like to create Terms and Conditions Page for the website
> 
> ![image](https://private-user-images.githubusercontent.com/101971980/356113089-9cdcdacf-42f1-465f-acdc-8b249ed68f9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDY1NzIsIm5iZiI6MTcyMzEwNjI3MiwicGF0aCI6Ii8xMDE5NzE5ODAvMzU2MTEzMDg5LTljZGNkYWNmLTQyZjEtNDY1Zi1hY2RjLThiMjQ5ZWQ2OGY5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwODM3NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWIxYTE1OTIwMWQ0NThjNjhiNDFmYjAyODljMmM4MTYzN2MzMzFhNzQxZTc4OTQyY2FjOWQxZTc3ZjdlNDlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xsUwlRp3WWx6ln7DAsr_XjtNZEg8EkIK1od6WVM3zIs)
> 
> ### Use Case
> N/A
> 
> ### Benefits
> N/A
> 
> ### Add ScreenShots
> N/A
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @MastanSayyad , Go for it
All the Best
