### ISSUE TITLE
Add Scroll to Top Button Functionality 

### ISSUE THREAD

**Issue by MastanSayyad** [Trisha-tech/OnlineBookSales#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Trisha-tech 

 I would like to create and add a scroll to top button functionality to the website
upon clicking on the button the page will scroll smoothly back to the top of the page reducing manual scrolling and increasing User Experince.

![image](https://github.com/user-attachments/assets/0c78f7fa-e31e-48e5-8557-4803d242cc76)

### Use Case

- It will be easier for the users to scroll back to the top of the page reducing the manual scrolling
- I will add Smooth Hover effects 
- Animations
- the button will only appear when scroll down a bit
- Responsive design.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Hey @Trisha-tech
> 
> I would like to create and add a scroll to top button functionality to the website upon clicking on the button the page will scroll smoothly back to the top of the page reducing manual scrolling and increasing User Experince.
> 
> ![image](https://private-user-images.githubusercontent.com/101971980/356118877-0c78f7fa-e31e-48e5-8557-4803d242cc76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDY1NjksIm5iZiI6MTcyMzEwNjI2OSwicGF0aCI6Ii8xMDE5NzE5ODAvMzU2MTE4ODc3LTBjNzhmN2ZhLWUzMWUtNDhlNS04NTU3LTQ4MDNkMjQyY2M3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwODM3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWIxMDI0NmNlNzhhOTMxODIwNWZiOWZmMTczZjQ1MGRhNGUzMDZiYzc1MzE1NjY5OGU4MDhjYjQ4ZGZiZDg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KQbt2sh4KnnVW8tyu9-Z-poEuRpHBnbePD4ukcNK5dc)
> 
> ### Use Case
> * It will be easier for the users to scroll back to the top of the page reducing the manual scrolling
> * I will add Smooth Hover effects
> * Animations
> * the button will only appear when scroll down a bit
> * Responsive design.
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @MastanSayyad , Go for it
All the Best
