### ISSUE TITLE
Create Our Contributors Page

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Trisha-tech/OnlineBookSales#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Trisha-tech 

I would like to create a dedicated Contributors Page. This page will acknowledge and appreciate all the contributors who have participated in the development of our project.

![image](https://github.com/user-attachments/assets/b0146432-4455-4590-9220-01cb6f8136c5)

**like this**

![image](https://github.com/user-attachments/assets/bfea463f-13db-40ce-a096-ff04e1c7797c)

### Use Case

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by DivyaJyothi9** [comment]
Hi, I’m interested in creating the Contributors page for this project. I have experience in HTML, CSS, JavaScript, and React, and I’d love to help design and implement this page. Could you please assign this issue to me?

Thank you!

**Comment by Trisha-tech** [comment]
> Hi, I’m interested in creating the Contributors page for this project. I have experience in HTML, CSS, JavaScript, and React, and I’d love to help design and implement this page. Could you please assign this issue to me?
> 
> Thank you!

Hello @DivyaJyothi9, This issue has been completed.
