### ISSUE TITLE
BUG: The Contact Us Page is Not Responsive

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Trisha-tech/OnlineBookSales#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @Trisha-tech 

Currently, our Contact Us Page is not responsive, which affects its usability across different devices and screen sizes. This issue needs to be addressed to ensure a consistent user experience across all platforms.

![image](https://github.com/user-attachments/assets/b2de58a3-203a-44f8-842e-50a21caabc32)

### Expected behavior

The Contact Us Page should display and function properly on mobile devices.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> Hey @Trisha-tech
> 
> Currently, our Contact Us Page is not responsive, which affects its usability across different devices and screen sizes. This issue needs to be addressed to ensure a consistent user experience across all platforms.
> 
> ![image](https://private-user-images.githubusercontent.com/163530398/356125249-b2de58a3-203a-44f8-842e-50a21caabc32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDY1NTQsIm5iZiI6MTcyMzEwNjI1NCwicGF0aCI6Ii8xNjM1MzAzOTgvMzU2MTI1MjQ5LWIyZGU1OGEzLTIwM2EtNDRmOC04NDJlLTUwYTIxY2FhYmMzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwODM3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzY0NzA0Y2IzNjEzZGIyMWZiMzg1NGQwYjZkMmNlNmE2ZDE3NjU1YTBmYzhhMjEzOWYxMTNhNzRmMTNjOGU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-x8jjsniiGycbRucKW53kmZQkD_MLVBjKQ251iqXTkY)
> 
> ### Expected behavior
> The Contact Us Page should display and function properly on mobile devices.
> 
> ### Add ScreenShots
> _No response_
> 
> ### On which device are you experiencing this bug?
> _No response_
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @RadhikaMalpani1702 , Go for it
All the Best
