### ISSUE TITLE
 Enhance Vertical Scrollbar to Match Website Design Theme

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Trisha-tech/OnlineBookSales#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Trisha-tech 

The current vertical scrollbar on our website does not align with the design theme. Enhancing the scrollbar to better match the overall website aesthetics will improve user experience and visual consistency.

![image](https://github.com/user-attachments/assets/5eabcbfb-1840-40a0-97c6-58f8583c14dd)

### Use Case

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Hey @Trisha-tech
> 
> The current vertical scrollbar on our website does not align with the design theme. Enhancing the scrollbar to better match the overall website aesthetics will improve user experience and visual consistency.
> 
> ![image](https://private-user-images.githubusercontent.com/163530398/356128940-5eabcbfb-1840-40a0-97c6-58f8583c14dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDY1NTEsIm5iZiI6MTcyMzEwNjI1MSwicGF0aCI6Ii8xNjM1MzAzOTgvMzU2MTI4OTQwLTVlYWJjYmZiLTE4NDAtNDBhMC05N2M2LTU4Zjg1ODNjMTRkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwODM3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2NiNzVkNGI2NzY5MDJjOGRjOGUwMjkzMWVjOGExZGJhNGZmYmM1MjU4YmM1ZjI3ZGI0NjcxMWFkNzU0NjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eCyxOK2SaZn2sm2pObTIuy6HkhxXDDPL_RuPWyiAgSk)
> 
> ### Use Case
> N/A
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @RadhikaMalpani1702 , Go for it
All the Best
