### ISSUE TITLE
[Bug]:  Missing spacing in WishList Page

### ISSUE THREAD

**Issue by Sourabh782** [Trisha-tech/OnlineBookSales#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In WishList Page there is missing of proper spacing, so in case of error both navbar and footer come together

### Expected behavior

There should be proper spacing in wishlist section

### Add ScreenShots

![Screenshot 2024-08-08 150139](https://github.com/user-attachments/assets/3dfbaed6-89fc-4a41-9e62-eeac68cefa4b)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> In WishList Page there is missing of proper spacing, so in case of error both navbar and footer come together
> 
> ### Expected behavior
> There should be proper spacing in wishlist section
> 
> ### Add ScreenShots
> ![Screenshot 2024-08-08 150139](https://private-user-images.githubusercontent.com/103349890/356165216-3dfbaed6-89fc-4a41-9e62-eeac68cefa4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjIyMjIsIm5iZiI6MTcyMzIyMTkyMiwicGF0aCI6Ii8xMDMzNDk4OTAvMzU2MTY1MjE2LTNkZmJhZWQ2LTg5ZmMtNGE0MS05ZTYyLWVlYWM2OGNlZmE0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxNjQ1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmFiOWE2NTU0YWM4YTIxZmNiNTc3YWQ3NjA0YWU3OGJjMTVkMzU4MmM1NjllNTQ1OWY1MjQ2YTBmNjA0ODVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FC6K-PoKHlUlM2GmWTpAiYVNOvnaPpjRUbTqndrcEVk)
> 
> ### On which device are you experiencing this bug?
> Chrome
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Sourabh782 , Go for it
All the Best

**Comment by Sourabh782** [comment]
Sure will be working on it
