### ISSUE TITLE
Create Licensing Page Reflecting MIT License

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Trisha-tech/OnlineBookSales#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Trisha-tech 

We need to create a dedicated Licensing page for the website, ensuring that it clearly reflects the terms of the MIT License under which the project is distributed. This page should be informative, well-designed, and aligned with the overall aesthetics of our website.

![image](https://github.com/user-attachments/assets/5ebef292-e2df-4700-92b8-6d3ab518f2b5)

**like this** 

![image](https://github.com/user-attachments/assets/1468fb72-95ad-4464-865d-05ab5e242b70)

### Use Case

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Hey @Trisha-tech
> 
> We need to create a dedicated Licensing page for the website, ensuring that it clearly reflects the terms of the MIT License under which the project is distributed. This page should be informative, well-designed, and aligned with the overall aesthetics of our website.
> 
> ![image](https://private-user-images.githubusercontent.com/163530398/356195253-5ebef292-e2df-4700-92b8-6d3ab518f2b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjIyOTIsIm5iZiI6MTcyMzIyMTk5MiwicGF0aCI6Ii8xNjM1MzAzOTgvMzU2MTk1MjUzLTVlYmVmMjkyLWUyZGYtNDcwMC05MmI4LTZkM2FiNTE4ZjJiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxNjQ2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzE2NWZhZDI4ZmExN2UxZWQ1MzdmYmM0NjUzMDY2ZTM0MzI0OTZhYmYyOTNiZTkzMjRkMjc2NTE4NTk3NmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l1w507c10CxZ4E6rs4PamkSfm7gcVm7KE6NWB0kskCE)
> 
> **like this**
> 
> ![image](https://private-user-images.githubusercontent.com/163530398/356197111-1468fb72-95ad-4464-865d-05ab5e242b70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjIyOTIsIm5iZiI6MTcyMzIyMTk5MiwicGF0aCI6Ii8xNjM1MzAzOTgvMzU2MTk3MTExLTE0NjhmYjcyLTk1YWQtNDQ2NC04NjVkLTA1YWI1ZTI0MmI3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxNjQ2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGZmYzYzMGNkMTRlNjk0ZDc0MTEyOTk1NDI5NzdiZTI3ZWU1NjA1MmZiY2JmZGI4NjljMWQ5YmIzMGM2ZTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cQck7LSNl8mGLu9pwKLmwp2n6VvKITWZ73sDNVlQu5I)
> 
> ### Use Case
> N/A
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @RadhikaMalpani1702 , Go for it
All the Best
