### ISSUE TITLE
 Add A News Letter Section 

### ISSUE THREAD

**Issue by MastanSayyad** [Trisha-tech/OnlineBookSales#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Trisha-tech 

I would like to add a newsletter section in the empty space of footer 

**Like this:**

![image](https://github.com/user-attachments/assets/bdb8286b-0549-45a5-b22a-d2c18084ea46)

### Use Case

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Hey @Trisha-tech
> 
> I would like to add a newsletter section in the empty space of footer
> 
> **Like this:**
> 
> ![image](https://private-user-images.githubusercontent.com/101971980/356414848-bdb8286b-0549-45a5-b22a-d2c18084ea46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjI0MDksIm5iZiI6MTcyMzIyMjEwOSwicGF0aCI6Ii8xMDE5NzE5ODAvMzU2NDE0ODQ4LWJkYjgyODZiLTA1NDktNDVhNS1iMjJhLWQyYzE4MDg0ZWE0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxNjQ4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODQ3OGJhOGRlYjg2MWJjYzA5NTE2OTI4NmRjZWQzMTQ1ZWM4ZDJhY2I0NzAwZTA1YzhlZWM0MDU4NjM5ZGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BKkrwfU3BpgGubwq1uD2p1Q__qbyUGEWs9C0d92U9DQ)
> 
> ### Use Case
> N/A
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @MastanSayyad , Go for it
All the Best
