### ISSUE TITLE
[Bug]: Routes access when not logged in.

### ISSUE THREAD

**Issue by tarunkumar2005** [Trisha-tech/OnlineBookSales#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@Trisha-tech So i saw the website and i noticed some things like when the user is not logged in and we try to go in shop, wishlist, cart or orders these routes should not be available and the user should be asked to login to access these or redirected to login page or / main page right so i want to fix this issue. Assign me on this under GSSOC'24 extd and hacktoberfest'24.

### Expected behavior

I already explained we should show a pop up that these can be only accessed after login or redirect to login page show the popup that only available after login or redirect to main page / and show the popup or toast to login first insted to seeing errors in it.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a48b5b2a-ed3f-4a95-aca8-a07f71495cdb)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> @Trisha-tech So i saw the website and i noticed some things like when the user is not logged in and we try to go in shop, wishlist, cart or orders these routes should not be available and the user should be asked to login to access these or redirected to login page or / main page right so i want to fix this issue. Assign me on this under GSSOC'24 extd and hacktoberfest'24.
> 
> ### Expected behavior
> I already explained we should show a pop up that these can be only accessed after login or redirect to login page show the popup that only available after login or redirect to main page / and show the popup or toast to login first insted to seeing errors in it.
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/158801564/372491300-a48b5b2a-ed3f-4a95-aca8-a07f71495cdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDMxMDIsIm5iZiI6MTcyNzgwMjgwMiwicGF0aCI6Ii8xNTg4MDE1NjQvMzcyNDkxMzAwLWE0OGI1YjJhLWVkM2YtNGE5NS1hY2E4LWEwN2Y3MTQ5NWNkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxNzEzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2Y1MjYzNWMyMWRmZTg5MTJjMDZlZjljMDIwZjI2MjM0NTBhOWIzZjI0MzY0NjA2ZTU5ZDBlOTI3NWZmNzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZFNLrNJpK7HVNruB49JlnJvT26qTRIFCDpqEqDtf1no)
> 
> ### On which device are you experiencing this bug?
> _No response_
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @tarunkumar2005, Go for it
All the Best

**Comment by tarunkumar2005** [comment]
add labels gssoc 2024 ext and hacktoberfest labels in this @Trisha-tech

**Comment by tarunkumar2005** [comment]
I want to give a suggestion @Trisha-tech like i have done this but the animations of changing screens means when you first  open the books animation is good but it is not good everytime you change the screen right it will be very boring and hectic and in this case where user clicks on the wishlist and not logged so it will show a toast that it can be only accessed after login so 2-3 goes in animation, then it opens and quickly redirects and in redirect again animation shows up so there also waiting time so the toast isn't properly visible in this time i tried to add custom time for toast and timeout but the animated screen after every page switch is frustating even for users i think who will use it try to put only on the first load or major change okay not every time screen switches i hope you will solve this. I have done my part i will create the pull request check on that it will work properly if you fix that animation i told just now. I hope you will consider this i can also help this new issue i just told create a new issue and asign it to me.

**Comment by Trisha-tech** [comment]
> add labels gssoc 2024 ext and hacktoberfest labels in this @Trisha-tech

This project is not under Hacktoberfest @tarunkumar2005 .

**Comment by Trisha-tech** [comment]
> I want to give a suggestion @Trisha-tech like i have done this but the animations of changing screens means when you first open the books animation is good but it is not good everytime you change the screen right it will be very boring and hectic and in this case where user clicks on the wishlist and not logged so it will show a toast that it can be only accessed after login so 2-3 goes in animation, then it opens and quickly redirects and in redirect again animation shows up so there also waiting time so the toast isn't properly visible in this time i tried to add custom time for toast and timeout but the animated screen after every page switch is frustating even for users i think who will use it try to put only on the first load or major change okay not every time screen switches i hope you will solve this. I have done my part i will create the pull request check on that it will work properly if you fix that animation i told just now. I hope you will consider this i can also help this new issue i just told create a new issue and asign it to me.

This project is for the contributors. So, one is free to modify , add and enhance the features. Create the issue by yourself based on requirement and I will assign it to you.

**Comment by tarunkumar2005** [comment]
@Trisha-tech I have putted the pull request you can verify and merge it.
