### ISSUE TITLE
[Feature Request]: Improved in Search and input button 

### ISSUE THREAD

**Issue by justynigam** [Trisha-tech/OnlineBookSales#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

it will look much good and can make your website more good 

### Use Case

none

### Benefits

it can look good in website for search

### Add ScreenShots

none

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by srajan07** [comment]
can you assign this issue to me

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> it will look much good and can make your website more good
> 
> ### Use Case
> none
> 
> ### Benefits
> it can look good in website for search
> 
> ### Add ScreenShots
> none
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @justynigam, Go for it
All the Best

**Comment by harish08102004** [comment]
Hey @Trisha-tech I can work on this.

**Comment by Trisha-tech** [comment]
> Hey @Trisha-tech I can work on this.

Hello @harish08102004 , Go for it
All the Best

**Comment by harish08102004** [comment]
Hey @Trisha-tech I'm not able to run the code in my local 
![image](https://github.com/user-attachments/assets/de96a19c-e90a-4f71-af5a-357c30c5a48b)
I'm getting this what should I do.

**Comment by Trisha-tech** [comment]
> Hey @Trisha-tech I'm not able to run the code in my local ![image](https://private-user-images.githubusercontent.com/116169377/373962350-de96a19c-e90a-4f71-af5a-357c30c5a48b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTk2ODAsIm5iZiI6MTcyODI5OTM4MCwicGF0aCI6Ii8xMTYxNjkzNzcvMzczOTYyMzUwLWRlOTZhMTljLWU5MGEtNGY3MS1hZjVhLTM1N2MzMGM1YTQ4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxMTA5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjhhNjZjYzViZTgzZmI4YjM1YzAwMWE4YmQ0MzJlMmU5NWQ1OGYxNDQ5ZDY0NTI3ODM4NjRhMGQ5NDNhNTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oL9i8D5XUdI1cbWOyEWoPRt1OpSvtPF_WGDOo7-qH0k) I'm getting this what should I do.

Kindly specify how did you ran the code.
Refer to the Readme file once on how to contribute to the project. If still you are facing the issue, feel free to contact.

**Comment by harish08102004** [comment]
Hey @Trisha-tech  I did follow everything in the readme file.
But still getting the same page.

Is the .env same as in .env.sample?
![image](https://github.com/user-attachments/assets/e36ea7f3-b7df-48da-817e-dd851e48f919)

**Comment by harish08102004** [comment]
Hey @Trisha-tech is it looks good or do I need to change it.

https://github.com/user-attachments/assets/4d36bbe2-fff8-4b6a-afcb-fd637e355e0f

**Comment by Trisha-tech** [comment]
> Hey @Trisha-tech is it looks good or do I need to change it. I feel the color of the search bar matches the UI.
> 
>  Online.book.mp4

Kindly add the search section either on the navbar or below the Home Page poster @justynigam

**Comment by harish08102004** [comment]
Hey @Trisha-tech I'm working on this not justynigam

**Comment by harish08102004** [comment]
https://github.com/user-attachments/assets/cdecfa27-c991-41fe-9113-b0624bdd6660

Will it work?

**Comment by Trisha-tech** [comment]
> @Trisha-tech https://github.com/user-attachments/assets/cdecfa27-c991-41fe-9113-b0624bdd6660
> 
> Will it work?

Yes, it will but keep only the search input and remove the extra gradient as it is not matching with the website theme. @harish08102004

**Comment by harish08102004** [comment]
ok

**Comment by harish08102004** [comment]
@Trisha-tech now ?

**Comment by harish08102004** [comment]
Ok I will raise the PR then.
