### ISSUE TITLE
Add Login page UI 

### ISSUE THREAD

**Issue by ArtiGaund** [Trisha-tech/OnlineBookSales#26]
Want to add login form using email and password with Oauth of google

**Comment by Trisha-tech** [comment]
> Want to add login form using email and password with Oauth of google

Already Assigned @ArtiGaund

**Comment by ArtiGaund** [comment]
@Trisha-tech  there is Oauth with google, but I didn't see Login page UI issue

**Comment by Aman0413** [comment]
I can make login page using tailwind. Could you please assign to me ?

**Comment by aasthakourav20** [comment]
Hey Trisha-tech , this issue isn't assigned to anyone . Would you please assign this to me

**Comment by ArtiGaund** [comment]
Already assigned issue #5

**Comment by ArtiGaund** [comment]
Already assigned
