### ISSUE TITLE
[Bug]: Addition of sort options in order page

### ISSUE THREAD

**Issue by Sourabh782** [Trisha-tech/OnlineBookSales#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently the orders page sort button not working

### Expected behavior

I wanted to add a proper dropdown to select options for sorting

### Add ScreenShots

![Screenshot 2024-10-02 115039](https://github.com/user-attachments/assets/010451aa-3463-4b69-9d50-1aac7eaec65f)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> Currently the orders page sort button not working
> 
> ### Expected behavior
> I wanted to add a proper dropdown to select options for sorting
> 
> ### Add ScreenShots
> ![Screenshot 2024-10-02 115039](https://private-user-images.githubusercontent.com/103349890/372750209-010451aa-3463-4b69-9d50-1aac7eaec65f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTE4MDcsIm5iZiI6MTcyNzg1MTUwNywicGF0aCI6Ii8xMDMzNDk4OTAvMzcyNzUwMjA5LTAxMDQ1MWFhLTM0NjMtNGI2OS05ZDUwLTFhYWM3ZWFlYzY1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNjQ1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTM4MzI0M2M4ZDM5ZmI3NmQyZTE0NjkxYmYzMjM5ODlkNWY4MzIyYjAwMjNiYWU5MjMwZmU0Njg4ODRlYmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xWGg9S2EOA5G1R7vNYKCCLSkjaw93yE6XJAzMQXdXj0)
> 
> ### On which device are you experiencing this bug?
> Windows
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Sourabh782, Go for it
All the Best

**Comment by Shalinis19137** [comment]
In above screen shot page of Bokk4U the heading orders are not arranged properly. Can you assign me this issue

**Comment by Shalinis19137** [comment]
In above screen shot page of Bokk4U the heading orders are not arranged properly. Can you assign me this issue

**Comment by Sourabh782** [comment]
Hey @Shalinis19137, create a new issue under issues tab to get a issue assigned and also it's aligned properly
