### ISSUE TITLE
[Feature Request]: I want to create frontend for your New arrivals book with card component and swiper js

### ISSUE THREAD

**Issue by VinayLodhi1712** [Trisha-tech/OnlineBookSales#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

creating frontend for your new arrival book with card component with demo data.
and want to add review section on home page at last above footer 

![customers](https://github.com/user-attachments/assets/3ee84bd5-106a-4906-b12b-2e69671ae2cf)

### Use Case

Now your project look like this 
![book](https://github.com/user-attachments/assets/f6acaa14-0372-4504-a59d-638d7889aa5f)

### Benefits

Good user interface and top books available show on home page but with demo data right now

### Add ScreenShots

![book](https://github.com/user-attachments/assets/e0dcfe4a-d8ce-4ec2-bcd4-d4e53e005a97)
![customers](https://github.com/user-attachments/assets/95a12a85-c964-4997-9a0f-498835453384)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

assign this issue under gssoc extended and hactoberfest

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> creating frontend for your new arrival book with card component with demo data. and want to add review section on home page at last above footer
> 
> ![customers](https://private-user-images.githubusercontent.com/135756009/372859099-3ee84bd5-106a-4906-b12b-2e69671ae2cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODE5NDUsIm5iZiI6MTcyNzg4MTY0NSwicGF0aCI6Ii8xMzU3NTYwMDkvMzcyODU5MDk5LTNlZTg0YmQ1LTEwNmEtNDkwNi1iMTJiLTJlNjk2NzFhZTJjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNTA3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDU3MzkyMjZmMTE1MDhmZWI2ZGQ0N2Q5NzI4YzA2NzllYzAzNzc5MWNlODM3Mzc5Zjg0YzM5NTJmOTNkYTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GiowRQ1pg0V4cYQU_hiSVoHAZz2mHttWgqawJS-ENes)
> 
> ### Use Case
> Now your project look like this ![book](https://private-user-images.githubusercontent.com/135756009/372859308-f6acaa14-0372-4504-a59d-638d7889aa5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODE5NDUsIm5iZiI6MTcyNzg4MTY0NSwicGF0aCI6Ii8xMzU3NTYwMDkvMzcyODU5MzA4LWY2YWNhYTE0LTAzNzItNDUwNC1hNTlkLTYzOGQ3ODg5YWE1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNTA3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWRjZjM5NTdmNmNlNmRiMGUxYWM5Y2Q1NWEzNDVkNGZkZWZiMmFiMTBiYjMxMTkyMjQ0YzM5OGUxMmZlZDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cq6_qPmirzlEBgBY36DlwNtYBL6CPRVN5K8J22ugdoU)
> 
> ### Benefits
> Good user interface and top books available show on home page but with demo data right now
> 
> ### Add ScreenShots
> ![book](https://private-user-images.githubusercontent.com/135756009/372859478-e0dcfe4a-d8ce-4ec2-bcd4-d4e53e005a97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODE5NDUsIm5iZiI6MTcyNzg4MTY0NSwicGF0aCI6Ii8xMzU3NTYwMDkvMzcyODU5NDc4LWUwZGNmZTRhLWQ4Y2UtNGVjMi1iY2Q0LWQ0ZTUzZTAwNWE5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNTA3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzg4ZGVkMDYwZjBiYjc4MzBiNjIzNjgzYjUwZDMzNWEwMzc4MWQzMTZlMTNjYTYwZjM0NjM3ZTliZjZkYTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kyPioUlz-tOBvUYL4DvA8Nb10450vejxIDVIB0fUlbU) ![customers](https://private-user-images.githubusercontent.com/135756009/372859494-95a12a85-c964-4997-9a0f-498835453384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODE5NDUsIm5iZiI6MTcyNzg4MTY0NSwicGF0aCI6Ii8xMzU3NTYwMDkvMzcyODU5NDk0LTk1YTEyYTg1LWM5NjQtNDk5Ny05YTBmLTQ5ODgzNTQ1MzM4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNTA3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2Y1NjI5NTQ3NzRkYzNjNDYwMDQ0YTRhOGYzZDgyNDlhZTczMzEzYWZjOWIxY2ZjNjkzOTk3Y2ZiYjY5MGI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.S9MQ4F6lldYr7-XbgemoUbXGipoTqyw7jL6PVIj-xmM)
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository
> 
> assign this issue under gssoc extended and hactoberfest

Hello @VinayLodhi1712 , Go for it
All the Best
