### ISSUE TITLE
[Feature Request]: Integrate Google Sign-In for User Authentication

### ISSUE THREAD

**Issue by pushkardev123** [Trisha-tech/OnlineBookSales#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Overview: The addition of Google Sign-In would streamline user authentication by allowing users to sign in to the OnlineBookSales platform with their Google accounts. This feature will simplify the login process, improve security through OAuth 2.0, and reduce the friction of manual account creation.

Proposed Implementation:

Frontend: Add a "Sign in with Google" button on the login and sign-up pages. Upon clicking the button, the user will be prompted to authenticate using their Google account.

Backend: Once authenticated, the backend should verify the received ID token using Google’s OAuth 2.0 API. A new user account will be created for first-time logins, and existing users will be logged in automatically if their Google account is linked to their profile.

Expected Outcome:

Users will be able to sign in without needing to manually input their email and password, improving ease of access.
Security will be enhanced since OAuth 2.0 is a more secure authentication method.

### Use Case

As a user of the Online Book Sales web application,
I want to be able to sign in using my Google account,
so that I can quickly and securely log in without the need to create a new account or remember a new set of credentials.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Overview: The addition of Google Sign-In would streamline user authentication by allowing users to sign in to the OnlineBookSales platform with their Google accounts. This feature will simplify the login process, improve security through OAuth 2.0, and reduce the friction of manual account creation.
> 
> Proposed Implementation:
> 
> Frontend: Add a "Sign in with Google" button on the login and sign-up pages. Upon clicking the button, the user will be prompted to authenticate using their Google account.
> 
> Backend: Once authenticated, the backend should verify the received ID token using Google’s OAuth 2.0 API. A new user account will be created for first-time logins, and existing users will be logged in automatically if their Google account is linked to their profile.
> 
> Expected Outcome:
> 
> Users will be able to sign in without needing to manually input their email and password, improving ease of access. Security will be enhanced since OAuth 2.0 is a more secure authentication method.
> 
> ### Use Case
> As a user of the Online Book Sales web application, I want to be able to sign in using my Google account, so that I can quickly and securely log in without the need to create a new account or remember a new set of credentials.
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @pushkardev123, Go for it
All the Best

**Comment by Dr-209** [comment]
Hi,
I would like to work on this project. I have experience with Node.js and Express.js, and I’m confident I can implement Google Sign-In authentication. Could you please assign this issue to me?

Looking forward to contributing!
