### ISSUE TITLE
Working on the user authentication in the sign up page

### ISSUE THREAD

**Issue by Lanaanvar** [Trisha-tech/OnlineBookSales#283]
Currently the sign up page is not working. It is showing 'error occurred'. 
![image](https://github.com/user-attachments/assets/7f5f3e97-101a-4521-a3dd-e3ee36b7f887)
I would like to work on this issue. Please assign this to me.

**Comment by Trisha-tech** [comment]
> Currently the sign up page is not working. It is showing 'error occurred'. ![image](https://private-user-images.githubusercontent.com/118440051/373230739-7f5f3e97-101a-4521-a3dd-e3ee36b7f887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTY1MDksIm5iZiI6MTcyNzk1NjIwOSwicGF0aCI6Ii8xMTg0NDAwNTEvMzczMjMwNzM5LTdmNWYzZTk3LTEwMWEtNDUyMS1hM2RkLWUzZWUzNmI3Zjg4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMTUwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmYxZGM4MDhlNWNkNTFjODM2ODVhZTc0NWY1ZTBlNzg2ZWYwYzIyYWU0OTBmNDQyN2YzOThlOTUyYWFlNzQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TpkcGQC2WU7-KoHVfPb2uVixXO01g9ATxfs_wQ74LuA) I would like to work on this issue. Please assign this to me.

Hello @Lanaanvar, Go for it
All the Best
