### ISSUE TITLE
[Feature Request]:  Hover effect for book and genre categories

### ISSUE THREAD

**Issue by Monu2114** [Trisha-tech/OnlineBookSales#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

User should have smooth ui experience by getting hover styling for components

### Use Case

User clicking on categories

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> User should have smooth ui experience by getting hover styling for components
> 
> ### Use Case
> User clicking on categories
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Monu2114, Go for it
All the Best

**Comment by Monu2114** [comment]
hey i have closed two issues right ? then why didnt the second issue count
didnt get updated in my gssoc leaderboard ?
