### ISSUE TITLE
[Feature Request]: Update the login page

### ISSUE THREAD

**Issue by NK-Works** [Trisha-tech/OnlineBookSales#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/408acea1-d5aa-4f6f-8157-08b99f3e3a07)
I can make the login ui much better,,,
dont forget to add the labels...
thanks:)

### Use Case

I can make the login ui professional, modern and sleek rather and make it much better than the current basic buttons for the login 

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> ![image](https://private-user-images.githubusercontent.com/132702983/373368054-408acea1-d5aa-4f6f-8157-08b99f3e3a07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5ODEwMTMsIm5iZiI6MTcyNzk4MDcxMywicGF0aCI6Ii8xMzI3MDI5ODMvMzczMzY4MDU0LTQwOGFjZWExLWQ1YWEtNGY2Zi04MTU3LTA4Yjk5ZjNlM2EwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxODM4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTg3ZTEwNDQ4OWNmNTA4YTY3MDdkNmU0ZmY4NTY3MGVlZWY2OWJiMmQ2MmE5NTFkYjg0ZWJlOGE4OGNiNDZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3nR4XoqZnbU68QZCYrQocBDGIKIlRGmZ246cqmcfVW0) I can make the login ui much better,,, dont forget to add the labels... thanks:)
> 
> ### Use Case
> I can make the login ui professional, modern and sleek rather and make it much better than the current basic buttons for the login
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> Medium
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @NK-Works, Go for it
All the Best
