### ISSUE TITLE
Enhance the Dark Theme of the Website 

### ISSUE THREAD

**Issue by rajatsinghal02** [Trisha-tech/OnlineBookSales#290]
I want to Enhance the Dark theme of the website it not up to mark experience is not so good in dark mode.

![Screenshot_20241004_094015.jpg](https://github.com/user-attachments/assets/f1f588e8-6d83-4f84-89eb-cc3ea583dcef)

@Trisha-tech Please assign this issue to me.

**Comment by Suman373** [comment]
@rajatsinghal02 Assigning this to you. Good luck !

**Comment by Suman373** [comment]
@rajatsinghal02 Yes ! Best of luck !
