### ISSUE TITLE
[Feature Request]: Update the signup page

### ISSUE THREAD

**Issue by NK-Works** [Trisha-tech/OnlineBookSales#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/f7dea56e-6645-4c58-b6a6-0a69cab4b8ab)

### Use Case

I have already updated the login feature and I can also update signup page as well...
lemme do it...
dont forget the labels...
thanks:)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> ![image](https://private-user-images.githubusercontent.com/132702983/373567398-f7dea56e-6645-4c58-b6a6-0a69cab4b8ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMzIyMjQsIm5iZiI6MTcyODAzMTkyNCwicGF0aCI6Ii8xMzI3MDI5ODMvMzczNTY3Mzk4LWY3ZGVhNTZlLTY2NDUtNGM1OC1iNmE2LTBhNjljYWI0YjhhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQwODUyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDQ2NWU3MjQ5ZjhiMGU0OGNhYWY0ZDAwMGZkOWNiYTkyNGJjZGUzOWIxMWNkNWQ5ZjJlMjg5MmMwNTNhNzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VjUpqGAiyJrkcFpTZjK6sbV1bbTRAz4gWpeCcoXUcQM)
> 
> ### Use Case
> I have already updated the login feature and I can also update signup page as well... lemme do it... dont forget the labels... thanks:)
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> Medium
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @NK-Works, Go for it
All the Best
