### ISSUE TITLE
[Feature Request]: Adding Sign In with Google (Frontend)

### ISSUE THREAD

**Issue by NK-Works** [Trisha-tech/OnlineBookSales#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add the functionality for the sign in with google feature in the frontend where the frontend will send the `access_token` to the backend and then the backend will use the access token to send req to google and seek the user information....

### Use Case

In this issue I will only address the frontend as I have seen another issue for the login with google backend a few days earlier but if it is not implemented by the time i make the frontend then i will open another issue for the backend as well. 
make sure to add the labels...
thanks...

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suman373** [comment]
@NK-Works You can start working on it ! Good luck!
