### ISSUE TITLE
[Bug]: UI improvement of register page

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Trisha-tech/OnlineBookSales#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Add ScreenShots

<img width="440" alt="Screenshot 2024-10-05 at 7 07 49 PM" src="https://github.com/user-attachments/assets/d88a70fd-e06c-468e-aa27-e3cb2a345935">
This is a small fix and Ui the of this can be improved.  @Trisha-tech if you could assign me this task i will work on it immediatelty.

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suman373** [comment]
@T-Rahul-prabhu-38 Hi there ! Someone is already working on UI enhancement of the signup page. Please let it get reviewed and then you may modify it further.

**Comment by T-Rahul-prabhu-38** [comment]
ok can i add localstorage feature to it?

**Comment by Suman373** [comment]
> ok can i add localstorage feature to it? @Suman373

@T-Rahul-prabhu-38 You can create a separate issue for that. I will close this one

**Comment by T-Rahul-prabhu-38** [comment]
sure
