### ISSUE TITLE
[Feature Request]: Integration of Local storage

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Trisha-tech/OnlineBookSales#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description
this will create a local storage to store user credentials.

### Use Case
this is a **very crucial feature** as this can help in retriveing user credentials and also can be used to store JWT tokens when backend is introduced.

### Priority
High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by T-Rahul-prabhu-38** [comment]
@Suman373  can you assign me the level and tag aswell,Thank you!

**Comment by Suman373** [comment]
@T-Rahul-prabhu-38 Assigned. Good luck!

**Comment by T-Rahul-prabhu-38** [comment]
thank you :)

**Comment by T-Rahul-prabhu-38** [comment]
btw what will the level be assigned to this.

**Comment by T-Rahul-prabhu-38** [comment]
can this bug be fixed becasue im not able to work on it
<img width="1467" alt="Screenshot 2024-10-06 at 8 29 52 AM" src="https://github.com/user-attachments/assets/3ccbaefd-2cd7-41ad-9e07-567ac326368f">

**Comment by Suman373** [comment]
> btw what will the level be assigned to this.

You are storing the user cred in local storage and use react state for managing auth state right ? @Trisha-tech you may decide the level.

**Comment by Suman373** [comment]
> can this bug be fixed becasue im not able to work on it <img alt="Screenshot 2024-10-06 at 8 29 52 AM" width="1467" src="https://private-user-images.githubusercontent.com/167653990/373918879-3ccbaefd-2cd7-41ad-9e07-567ac326368f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxOTg5ODMsIm5iZiI6MTcyODE5ODY4MywicGF0aCI6Ii8xNjc2NTM5OTAvMzczOTE4ODc5LTNjY2JhZWZkLTJjZDctNDFhZC05ZTA3LTU2N2FjMzI2MzY4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQwNzExMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjdjNjg5MDE2ODM3Nzc2Mzc2ZDA5ZjMyODQwN2FlMTE5ZGY3MTg1ZTU1ODJiOTI4NWMxZWM1YzA3N2RkMTkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yDsVV7Mn0FVm4GTCARtXmrIvzk82mKvTuCueR0WkTWA">

Yes, you can fix it.
