### ISSUE TITLE
[Feature Request]: Confirm Password Field in Sign Up page

### ISSUE THREAD

**Issue by Ayan-Khan79** [Trisha-tech/OnlineBookSales#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/4c26f9a2-4fb0-4e17-b52e-fa8432fa4294)
The user registration form is missing a "Confirm Password" field. This is a common best practice in authentication forms to ensure that users do not accidentally enter the wrong password.
Can you please assign me this issue?

### Use Case

User: A person attempting to create a new account.
System: The application or website that handles user registration.

### Benefits

Typing mistakes in the password field are common. By having a "Confirm Password" field, users are prompted to enter the password twice, reducing the chance of errors and ensuring the password is what they intended.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> ![image](https://private-user-images.githubusercontent.com/151816474/373899415-4c26f9a2-4fb0-4e17-b52e-fa8432fa4294.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMDM1NDUsIm5iZiI6MTcyODIwMzI0NSwicGF0aCI6Ii8xNTE4MTY0NzQvMzczODk5NDE1LTRjMjZmOWEyLTRmYjAtNGUxNy1iNTJlLWZhODQzMmZhNDI5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQwODI3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWU5MWZiOWM5YjE5OGE5MWY2YjAyNjViOTk5NjFkMDFmN2JhODNiNzgxZDQxYzAyMmQwOTEyOTY3M2ZiODBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hduRPbPXDv4veMayFyqgEIaNaG_OJrlSSOy1OszDUYQ) The user registration form is missing a "Confirm Password" field. This is a common best practice in authentication forms to ensure that users do not accidentally enter the wrong password. Can you please assign me this issue?
> 
> ### Use Case
> User: A person attempting to create a new account. System: The application or website that handles user registration.
> 
> ### Benefits
> Typing mistakes in the password field are common. By having a "Confirm Password" field, users are prompted to enter the password twice, reducing the chance of errors and ensuring the password is what they intended.
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Ayan-Khan79, Go for it
All the Best

**Comment by Ayan-Khan79** [comment]
Can you please add the  lable of Hacktoberfest also?

**Comment by Suman373** [comment]
> @Trisha-tech Can you please add the lable of Hacktoberfest also?

We will. Give us some time to opt in for hacktoberfest first.

**Comment by Ayan-Khan79** [comment]
Task Completed!!!!

**Comment by Suman373** [comment]
@Ayan-Khan79 Hey, good work !!
