### ISSUE TITLE
[Documentation Update]: Update the README.md

### ISSUE THREAD

**Issue by NK-Works** [Trisha-tech/OnlineBookSales#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The readme.md is very jargon and not engaging at all.

### Suggested Change

I want to update the readme md to make it more readable and give engaging.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Issue Description
> The readme.md is very jargon and not engaging at all.
> 
> ### Suggested Change
> I want to update the readme md to make it more readable and give engaging.
> 
> ### Rationale
> _No response_
> 
> ### Urgency
> Medium
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @NK-Works, Go for it
All the Best
