### ISSUE TITLE
[Feature Request]: Adding Search Functionality with some data

### ISSUE THREAD

**Issue by Monu2114** [Trisha-tech/OnlineBookSales#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When the user is searching for a book, we can auto suggest things for searching books in such way : 
![Screenshot 2024-10-04 110650](https://github.com/user-attachments/assets/1439a7cb-8c3a-4a4f-a096-0425a7712215)

### Use Case

Users wont need to type the whole book name instead can browse their books easily

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> When the user is searching for a book, we can auto suggest things for searching books in such way : ![Screenshot 2024-10-04 110650](https://private-user-images.githubusercontent.com/116855819/373924166-1439a7cb-8c3a-4a4f-a096-0425a7712215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMDQwOTYsIm5iZiI6MTcyODIwMzc5NiwicGF0aCI6Ii8xMTY4NTU4MTkvMzczOTI0MTY2LTE0MzlhN2NiLThjM2EtNGE0Zi1hMDk2LTA0MjVhNzcxMjIxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQwODM2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTc5Y2Y3ZWE1NWFkY2YxYzFjNzgxMDcyMGE5ZjI1N2IyYWVhNGYwZTI5ZDMwMDg5ZWVlMzAyNWI0MjFjZjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vqIaicIWKCdGZtvyVZaoV2UeGVXfJyV64FTHD4or_0Q)
> 
> ### Use Case
> Users wont need to type the whole book name instead can browse their books easily
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Monu2114, Go for it
All the Best
