### ISSUE TITLE
[Feature] Creating reusable Book UI component

### ISSUE THREAD

**Issue by Monu2114** [Trisha-tech/OnlineBookSales#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The code is not at all effective in the homepage in book categories as well as trending books section . 
![image](https://github.com/user-attachments/assets/9c82cf8e-9a0c-43e4-a414-46f315c88853)

### Expected behavior

I want to optimise the book section genre by adding a card component for each book as the code wont be repetitive and the book components can be added easily and any style changes can be made to all the categories collectively other than updating features in each div element

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9cbb92e3-958e-42c6-a6cc-c36c9a911dec)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suman373** [comment]
Hi ! The issue label can be a feature - creating reusable Book UI component.
