### ISSUE TITLE
[Bug]: pages missing

### ISSUE THREAD

**Issue by puneeth072003** [Trisha-tech/OnlineBookSales#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

About section in the support bar contains few links that head no where.

I'd e happy to remove them or to add pages regarding them.

### Expected behavior

Should open up respective pages as the other links

### Add ScreenShots

![Screenshot 2024-10-07 010347](https://github.com/user-attachments/assets/150a3dba-dfad-44fd-9d08-465a08826585)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Suman373** [comment]
@puneeth072003 You may add new routes and blank pages for now. Assigning this to you !

**Comment by puneeth072003** [comment]
@Trisha-tech  Can you please add `hacktoberfest-accepted` label to my PR.
