### ISSUE TITLE
[Bug]: Huge number of unused variables in the code base

### ISSUE THREAD

**Issue by puneeth072003** [Trisha-tech/OnlineBookSales#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

while running my frontend i found warnings of  huge number of unused variables 

I'd be happy to remove them

### Expected behavior

clean codebase

### Add ScreenShots

![Screenshot 2024-10-07 130808](https://github.com/user-attachments/assets/cb56ecbc-12e4-40a9-a14d-e1aa20a2150f)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> while running my frontend i found warnings of huge number of unused variables
> 
> I'd be happy to remove them
> 
> ### Expected behavior
> clean codebase
> 
> ### Add ScreenShots
> ![Screenshot 2024-10-07 130808](https://private-user-images.githubusercontent.com/119479391/374080156-cb56ecbc-12e4-40a9-a14d-e1aa20a2150f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMTc3ODQsIm5iZiI6MTcyODMxNzQ4NCwicGF0aCI6Ii8xMTk0NzkzOTEvMzc0MDgwMTU2LWNiNTZlY2JjLTEyZTQtNDBhOS1hMTRkLWUxYWEyMGEyMTUwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxNjExMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWE5MjNjNzdjYjEwNDM1MDFlYjg0NDY3YmQyZGZkM2JiYzk5ZmY0NDAzNjJjMjFiYjRlNGM3YmJkMmFmMzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QrFTO8noc4PRTgISxeBH6-kh4Jn6paI_ne7f8ywBEqo)
> 
> ### On which device are you experiencing this bug?
> _No response_
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @puneeth072003, Go for it
All the Best

**Comment by arduvey29** [comment]
Hii @Trisha-tech I'd like to work on this issue, could you please assign it to me?

**Comment by puneeth072003** [comment]
@arduvey29 Sorry, I'm working on it.
