### ISSUE TITLE
[Feature Request]: What do you think about adding chat bot 

### ISSUE THREAD

**Issue by puneeth072003** [Trisha-tech/OnlineBookSales#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I'd like to take up this feature dev to addin te chat bot towards the right of the screen

Proposed tools that i'd like to use:
- Bootstrap
- [BotPress](https://botpress.com/)

### Use Case

It can help customers to clear their queries.

### Benefits

24/7 availability and instant replys to clear the problems of cutomers

### Add ScreenShots

None

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> I'd like to take up this feature dev to addin te chat bot towards the right of the screen
> 
> Proposed tools that i'd like to use:
> 
> * Bootstrap
> * [BotPress](https://botpress.com/)
> 
> ### Use Case
> It can help customers to clear their queries.
> 
> ### Benefits
> 24/7 availability and instant replys to clear the problems of cutomers
> 
> ### Add ScreenShots
> None
> 
> ### Priority
> Medium
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

This feature has already been addressed @puneeth072003.

**Comment by puneeth072003** [comment]
Ok I'll take it down
