### ISSUE TITLE
[Bug]: Fix the Register and Signup Issues

### ISSUE THREAD

**Issue by Trisha-tech** [Trisha-tech/OnlineBookSales#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently, the register and sign in functionality is not working properly. 

### Expected behavior

Register page should register the new user to the database. 
Sign in page should login the existing user to the website. 

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Revant-S** [comment]
@Trisha-tech I have good experience in MERN stack. Please assign this issue to me

**Comment by Achbi** [comment]
@Trisha-tech  Please assign me this issue

**Comment by ekayZ7875** [comment]
Hello @Trisha-tech i would like to work upon this issue.Please assign it to me.Although i have experience with your repository as i have contributed to it before.

**Comment by Trisha-tech** [comment]
> @Trisha-tech i want to work on the issue.. but before that would you clarify what database you are using as a backend

Hello @amitroy-thedev, Go for it
All the Best
Database: MongoDB

**Comment by amitroy-thedev** [comment]
Hey @Trisha-tech i thought the bug was large and i thought the codebase has some issue and it took me time to fix any bug but its not the problem was in the .env file or say .env.sample file.. i have fixed it and now its good to go you can check it

**Comment by amitroy-thedev** [comment]
![image](https://github.com/user-attachments/assets/dd6b7954-5431-4cef-9739-83c02ac238e6)
assign me here before closing and merging the issue
