### ISSUE TITLE
[Bug]: Customer Profile UI Sidebar Not Functional and Some Details are Missing

### ISSUE THREAD

**Issue by CodexRaunak** [Trisha-tech/OnlineBookSales#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The side bar is having tabs like profile info, address PAN card. Some tabs are missing like the PAN card and Saved UPI. I only designed this UI so I can work on it further and make it functional.
 

### Expected behavior

I will be adding a form where user can fill its PAN card info.
I will be adding a form to buy gift cards
Gift cards can be a strategic marketing and sales tool for e-commerce businesses, and can help to increase sales and profits

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1ffa8da4-56a6-49a3-835a-fe7473a01814)
When we click on PAN card it shows personal info.

I am gonna make it something like this
![image](https://github.com/user-attachments/assets/ac281a93-748f-466c-94fe-236905df6012)

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by CodexRaunak** [comment]
Can I work on this issue @Trisha-tech as previously worked on the Customer Profile UI page

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> The side bar is having tabs like profile info, address PAN card. Some tabs are missing like the PAN card and Saved UPI. I only designed this UI so I can work on it further and make it functional.
> 
> ### Expected behavior
> I will be adding a form where user can fill its PAN card info. I will be adding a form to buy gift cards Gift cards can be a strategic marketing and sales tool for e-commerce businesses, and can help to increase sales and profits
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/143412156/374273711-1ffa8da4-56a6-49a3-835a-fe7473a01814.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODA3NzQsIm5iZiI6MTcyODM4MDQ3NCwicGF0aCI6Ii8xNDM0MTIxNTYvMzc0MjczNzExLTFmZmE4ZGE0LTU2YTYtNDlhMy04MzVhLWZlNzQ3M2EwMTgxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwOTQxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTUxYTlkZjM1OTIxZDU4ZWFhM2E3MGI4MzI3ZmFkMzY0MjEwYzA4YmI3NWU3NTJiNDljZTlhODlmZTY5NDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0FpWNEdAgNP1FSJUXFJWwclmcj_jxp27yh9cImu1nZU) When we click on PAN card it shows personal info.
> 
> I am gonna make it something like this ![image](https://private-user-images.githubusercontent.com/143412156/374273867-ac281a93-748f-466c-94fe-236905df6012.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODA3NzQsIm5iZiI6MTcyODM4MDQ3NCwicGF0aCI6Ii8xNDM0MTIxNTYvMzc0MjczODY3LWFjMjgxYTkzLTc0OGYtNDY2Yy05NGZlLTIzNjkwNWRmNjAxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwOTQxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGRmNjM0MzBkNWI0YzI5MDMzZmQ0YzBmMjBhN2U5OTZiNWI3ZTc5YTg4YzhjZDUyOTE2ZjFhZTk3ZmJkNDA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.83UoMiOgm6AF_IPtDOWHvOsu-KSC_8KT3-dG3Frpdaw)
> 
> ### On which device are you experiencing this bug?
> Android, iPhone, Linux, Chrome, Windows
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @CodexRaunak, Go for it
All the Best

**Comment by CodexRaunak** [comment]
Hey sorry for the delay i am gonna make the PR tomorrow, the work is ongoing. I was having my exams going which made the work little slow.

**Comment by Suman373** [comment]
> Hey sorry for the delay i am gonna make the PR tomorrow, the work is ongoing. I was having my exams going which made the work little slow.

No worries.
