### ISSUE TITLE
[Bug]: ERR_HTTP_HEADERS_SENT more than once

### ISSUE THREAD

**Issue by CodexRaunak** [Trisha-tech/OnlineBookSales#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The error ERR_HTTP_HEADERS_SENT occurs when you try to set headers or send a response after the response has already been sent to the client. This is happening as we are calling res.json it multiple times. 

This is happening because we are not making this check in error handler middleware 
if (res.headersSent) 

### Expected behavior

The sever will only try to send response headers only if it hasn't been sent to the client. If it has been sent to the client then it will not try to send it again.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f631687e-e478-42c4-8d49-ea2e39029be7)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by CodexRaunak** [comment]
Can you assign it to me under GSSOC extd @Trisha-tech

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> The error ERR_HTTP_HEADERS_SENT occurs when you try to set headers or send a response after the response has already been sent to the client. This is happening as we are calling res.json it multiple times.
> 
> This is happening because we are not making this check in error handler middleware if (res.headersSent)
> 
> ### Expected behavior
> The sever will only try to send response headers only if it hasn't been sent to the client. If it has been sent to the client then it will not try to send it again.
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/143412156/374280382-f631687e-e478-42c4-8d49-ea2e39029be7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODA3NzYsIm5iZiI6MTcyODM4MDQ3NiwicGF0aCI6Ii8xNDM0MTIxNTYvMzc0MjgwMzgyLWY2MzE2ODdlLWU0NzgtNDJjNC04ZDQ5LWVhMmUzOTAyOWJlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwOTQxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDg5OGJlZmZjMzY4NTcxYTgzNTU0MzE4ZTY3YTNjM2UyYzk2ZjEyMDBmYjFkYTdmZGFjNjk5ODNkNDg3MzU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SLaA3rvXoIUZnirYKSrINhhKkhlSoGEhtTaWRpcP4i8)
> 
> ### On which device are you experiencing this bug?
> Windows
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Backend was working fine initially. Anyways, Go for it @CodexRaunak 
All the Best
