### ISSUE TITLE
Improving New Arrivals and Trending Books section

### ISSUE THREAD

**Issue by komalnalage** [Trisha-tech/OnlineBookSales#367]
Hi @Trisha-tech I would want to improve this section and make it more visually appealing.
![image](https://github.com/user-attachments/assets/5203bf77-5e2d-47fd-8601-172d6a53cbfe)
Could you assign me this task and add gssoc-ext and hactoberfest-accepted tags?

**Comment by Trisha-tech** [comment]
> Hi @Trisha-tech I would want to improve this section and make it more visually appealing. ![image](https://private-user-images.githubusercontent.com/148746389/374406064-5203bf77-5e2d-47fd-8601-172d6a53cbfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODMwNTQsIm5iZiI6MTcyODM4Mjc1NCwicGF0aCI6Ii8xNDg3NDYzODkvMzc0NDA2MDY0LTUyMDNiZjc3LTVlMmQtNDdmZC04NjAxLTE3MmQ2YTUzY2JmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMDE5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTM3ZTM1MzQ5OGRlNzk3ZWM5MjczZjg0NmUyNDcxNDNlMTRkNDhiODhlODg2N2RiNThjNmE5NTU0OTkwZDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZyQXoHlNZw5Ygh50t8lcLu_rjITldlKM-MdcTfC6r-c) Could you assign me this task and add gssoc-ext and hactoberfest-accepted tags?

Kindly follow the template for creating issue @komalnalage

**Comment by komalnalage** [comment]
Okay shall I re-raise an issue or can post it on this one?

**Comment by Trisha-tech** [comment]
> Okay shall I re-raise an issue or can post it on this one?

If template is available here in this issue, you can update it else create a new issue.

**Comment by komalnalage** [comment]
Hi @Trisha-tech will you close this issue as i will raise a new issue
