### ISSUE TITLE
Customer profile page UI

### ISSUE THREAD

**Issue by ArtiGaund** [Trisha-tech/OnlineBookSales#37]
Customer profile page will have certain section like
1) personal setting -> from where customer can modify their details. 
2) my order -> history of books order list
3) my wishlist 
4) change password
5) option to add location ( where they want delivery)

**Comment by Rajneeshkarya** [comment]
Hi @ArtiGaund, As a contributor to GSSOC'24, I would like to do this task under GSSOC'24. Could you please assign this issue to me?

**Comment by Trisha-tech** [comment]
> Customer profile page will have certain section like
> 
> 1. personal setting -> from where customer can modify their details.
> 2. my order -> history of books order list
> 3. my wishlist
> 4. change password
> 5. option to add location ( where they want delivery)

Hello @ArtiGaund , Go for it
All the Best

**Comment by ArtiGaund** [comment]
I can design User Profile page according to me?

**Comment by nishant0708** [comment]
assign me this issue under gssoc24

**Comment by Prashant-2024** [comment]
I would like to work under this issue under GSSOC'24. 
@Trisha-tech Please assign this issue to me.

**Comment by CodexRaunak** [comment]
Hey, I would like to work on this issue, please assign it to me under GSSOC '24 extd @Trisha-tech

**Comment by Trisha-tech** [comment]
> Hey, I would like to work on this issue, please assign it to me under GSSOC '24 extd @Trisha-tech

Hello @CodexRaunak, Go for it
All the Best

**Comment by CodexRaunak** [comment]
hey @Trisha-tech i am making a pr for this issue could you please add hacktoberfest-accepted label to it as well

**Comment by Trisha-tech** [comment]
> hey @Trisha-tech i am making a pr for this issue could you please add hacktoberfest-accepted label to it as well

@CodexRaunak This project is not participating  under Hacktoberfest 2024.
