### ISSUE TITLE
 Improving New Arrivals and Trending Books section

### ISSUE THREAD

**Issue by komalnalage** [Trisha-tech/OnlineBookSales#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Enhancing these two sections by adding hover effects and improving the layout

### Use Case

It would make the user experience better as it would be visually appealing

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ae31f5d2-04fe-43d4-9b52-ccdd151d65e7)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Enhancing these two sections by adding hover effects and improving the layout
> 
> ### Use Case
> It would make the user experience better as it would be visually appealing
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/148746389/374572638-ae31f5d2-04fe-43d4-9b52-ccdd151d65e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTQ1MzksIm5iZiI6MTcyODU1NDIzOSwicGF0aCI6Ii8xNDg3NDYzODkvMzc0NTcyNjM4LWFlMzFmNWQyLTA0ZmUtNDNkNC05YjUyLWNjZGQxNTFkNjVlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwOTU3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmNhODcwOGQ2YmQ4ODIyNzk0MjFjNGRmZWQ2Njk4MGI5MjcwNjQ2ZTdhOGZjNTNkYTE5ODMxNzgyY2I5YTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dKbGFsbLbXXOji_0PaXiWgi6-26alDerP4qkKKEeF1E)
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @komalnalage, Go for it
All the Best
New Arrivals has already been done. You can work on Trending Books and Book Categories section.

**Comment by komalnalage** [comment]
Thank you @Trisha-tech i will raise the PR once done
