### ISSUE TITLE
[Bug]: Scroll to top and chatbot overlapping

### ISSUE THREAD

**Issue by Sourabh782** [Trisha-tech/OnlineBookSales#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The chatbot and scroll to top button is overlapping

### Expected behavior

There should be gap between scroll to top and chatbot button

### Add ScreenShots

![Screenshot 2024-10-09 120639](https://github.com/user-attachments/assets/8fc1a9a8-09a9-4964-9334-83c886d0471d)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> Contributor

Hello @Sourabh782, Go for it
All the Best

**Comment by Sourabh782** [comment]
> > Contributor
> 
> Hello @Sourabh782, Go for it All the Best

Thanks @Trisha-tech, working on it
