### ISSUE TITLE
[Feature Request]: To auto scroll the customer reviews.

### ISSUE THREAD

**Issue by bm9240** [Trisha-tech/OnlineBookSales#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Since there is a section in the Home page where the customer reviews are displayed
i would like to add on a fuctionality where these reviews get auto scrolled horizontally making the page look visually more appealing.
I would also like to make the font of the reviews more readable.
The reviews will scrolled one by one in ever 3-4 seconds and after the last the first one will again be dispalyed.
Please assign me this task @Trisha-tech 
Looking forward to work on this Project !!

### Use Case

As a user the reviews are blandly displayed on the home page and to read more reviews I have to use buttons to move to the next review so if I would have seen an reviews page with an animation it would have attracted me and actually convinced me to read the content.

### Benefits

When the user reads positive feedback it increases the trust of the user on the website.
This would attract users to read the feedbacks and increase the usage of the website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Since there is a section in the Home page where the customer reviews are displayed i would like to add on a fuctionality where these reviews get auto scrolled horizontally making the page look visually more appealing. I would also like to make the font of the reviews more readable. The reviews will scrolled one by one in ever 3-4 seconds and after the last the first one will again be dispalyed. Please assign me this task @Trisha-tech Looking forward to work on this Project !!
> 
> ### Use Case
> As a user the reviews are blandly displayed on the home page and to read more reviews I have to use buttons to move to the next review so if I would have seen an reviews page with an animation it would have attracted me and actually convinced me to read the content.
> 
> ### Benefits
> When the user reads positive feedback it increases the trust of the user on the website. This would attract users to read the feedbacks and increase the usage of the website
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @bm9240, Go for it
All the Best

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Since there is a section in the Home page where the customer reviews are displayed i would like to add on a fuctionality where these reviews get auto scrolled horizontally making the page look visually more appealing. I would also like to make the font of the reviews more readable. The reviews will scrolled one by one in ever 3-4 seconds and after the last the first one will again be dispalyed. Please assign me this task @Trisha-tech Looking forward to work on this Project !!
> 
> ### Use Case
> As a user the reviews are blandly displayed on the home page and to read more reviews I have to use buttons to move to the next review so if I would have seen an reviews page with an animation it would have attracted me and actually convinced me to read the content.
> 
> ### Benefits
> When the user reads positive feedback it increases the trust of the user on the website. This would attract users to read the feedbacks and increase the usage of the website
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @bm9240, Go for it
All the Best

**Comment by bm9240** [comment]
Thank You ! @Trisha-tech 
I ll start working on it.
Meanwhile could you please assign me this task alongwith the gssoc and hacktoberfest labels and a level you feel that is suitable.
