### ISSUE TITLE
[Bug]: No left margin in left side of Book categories and new arrivals section 

### ISSUE THREAD

**Issue by nishtha-902** [Trisha-tech/OnlineBookSales#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No left margin in left side of Book categories and new arrivals section 

### Expected behavior

These both sections must be shifted slightly rightwards with proper margins

### Add ScreenShots

![image](https://github.com/user-attachments/assets/22146b16-f2a7-4dbf-8a12-ffc43756af1b)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> No left margin in left side of Book categories and new arrivals section
> 
> ### Expected behavior
> These both sections must be shifted slightly rightwards with proper margins
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/132751527/375043428-22146b16-f2a7-4dbf-8a12-ffc43756af1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDYwNDAsIm5iZiI6MTcyODY0NTc0MCwicGF0aCI6Ii8xMzI3NTE1MjcvMzc1MDQzNDI4LTIyMTQ2YjE2LWYyYTctNGRiZi04YTEyLWZmYzQzNzU2YWYxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMTIyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGQ4NGY0ZWNlNDkzNDlhODFjMDU4ZTVmMjJhNDY2OGViZWZlZGM5MzFiY2JhMWM5MDdiNDIwYjZlODdjNjY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7gaEgPhiCN9IS_QFx8XrKZOzjGX5r7j33kc1g9T7lLc)
> 
> ### On which device are you experiencing this bug?
> _No response_
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Kindly run the code locally. This issue has already been addressed. @nishtha-902
