### ISSUE TITLE
[Feature Request]: I want to add the google OAuth in the application.

### ISSUE THREAD

**Issue by krishpathak** [Trisha-tech/OnlineBookSales#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

User can log in directly with his /her email id.

### Use Case

Facilates user to register/login directly by registered email id.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by samriddhi122** [comment]
please assign this issue to me
