### ISSUE TITLE
[Feature Request]: Email validation to sign up page

### ISSUE THREAD

**Issue by meghanakn473** [Trisha-tech/OnlineBookSales#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

@Trisha-tech please assign this issue to me

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> @Trisha-tech please assign this issue to me
> 
> ### Use Case
> .
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @meghanakn473, Go for it
All the Best

**Comment by meghanakn473** [comment]
@Trisha-tech done !! please check and update, i hope ull consider it :)
