### ISSUE TITLE
[Feature Request]: Hovering effects to type of genre of books

### ISSUE THREAD

**Issue by meghanakn473** [Trisha-tech/OnlineBookSales#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@Trisha-tech please assign this issue to me

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> @Trisha-tech please assign this issue to me
> 
> ### Use Case
> .
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @meghanakn473, This issue has already been addressed.
