### ISSUE TITLE
[Bug]: FAQ section is not readable 

### ISSUE THREAD

**Issue by ABHI-SHEK-001** [Trisha-tech/OnlineBookSales#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

FAQ section is not clearly readable in light mode , i want to correct it

### Expected behavior

it should be readable 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/0b8269fb-d2c6-47e9-8178-2f0ebc297f1f)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> FAQ section is not clearly readable in light mode , i want to correct it
> 
> ### Expected behavior
> it should be readable
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/165279311/375377679-0b8269fb-d2c6-47e9-8178-2f0ebc297f1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDc3NzMsIm5iZiI6MTcyODY0NzQ3MywicGF0aCI6Ii8xNjUyNzkzMTEvMzc1Mzc3Njc5LTBiODI2OWZiLWQyYzYtNDdlOS04MTc4LTJmMGViYzI5N2YxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMTUxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmFmZWI0YWM3N2JjZTM4YjUzNjZmODhhN2ZhNWUzMGE1NmZhOGEwYjEyMzkyMTFkNTcyODRkNDY3MjYyOWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NEobtSu-A74o7UctB5g5bXhnPJwx-XrfW9BrlPFrMGo)
> 
> ### On which device are you experiencing this bug?
> _No response_
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @ABHI-SHEK-001, this issue has already been addressed.
