### ISSUE TITLE
[Bug]: Search Filter

### ISSUE THREAD

**Issue by darshinihoney** [Trisha-tech/OnlineBookSales#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I have typed the name of a book into the search bar and no matching book is found, there is no feedback or result shown. This creates confusion for the user, as they don't know if the search is still processing, if there was an error, or if the book simply doesn't exist in the database.

### Expected behavior

Display a pop-up card or message notifying the user that the book was not found.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> When I have typed the name of a book into the search bar and no matching book is found, there is no feedback or result shown. This creates confusion for the user, as they don't know if the search is still processing, if there was an error, or if the book simply doesn't exist in the database.
> 
> ### Expected behavior
> Display a pop-up card or message notifying the user that the book was not found.
> 
> ### Add ScreenShots
> _No response_
> 
> ### On which device are you experiencing this bug?
> _No response_
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @darshinihoney, Go for it
All the Best
