### ISSUE TITLE
Make change in css styling of navbar

### ISSUE THREAD

**Issue by gadeharshada** [Trisha-tech/OnlineBookSales#447]
![Screenshot (95)](https://github.com/user-attachments/assets/b23a794e-d9ab-4e2e-83a1-4c3b80efc0d0)
I am a gssoc'24 contributer ,I want to make changes in the navbar,
The Home button should be at front and login should be at last

**Comment by sanketdev1234** [comment]
please assign me this issue under gssoc24extd

**Comment by gadeharshada** [comment]
Please tell me how to assign this uder gssoc24extd and there was no option for labels

**Comment by gadeharshada** [comment]
> please assign me this issue under gssoc24extd

Please tell me how to assign this uder gssoc24extd and there is no option for selecting the labels

**Comment by sanketdev1234** [comment]
Are you admin of project?

**Comment by gadeharshada** [comment]
I am new to GitHub I don't know some things

**Comment by sanketdev1234** [comment]
I didn't understand what you are saying
