### ISSUE TITLE
[Bug]: Cart showing up when not logged in

### ISSUE THREAD

**Issue by NK-Works** [Trisha-tech/OnlineBookSales#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/3498a931-7b48-46bc-a6ad-02bc22edace0)
As you can see when clicked on the cart rather than showing you cart is empty and a login button it shows error.

### Expected behavior

I want to resolve the issue here

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by naitikhoriya1** [comment]
[Feature Request]: Add to cart #487
