### ISSUE TITLE
[Bug]: FAQ answer not visible

### ISSUE THREAD

**Issue by saumyayadav25** [Trisha-tech/OnlineBookSales#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img width="1362" alt="Screenshot 2024-10-12 at 6 35 28 PM" src="https://github.com/user-attachments/assets/fca74be0-3f08-4b97-b597-e5cab80d16a6">

FAQ answers not visible
No smooth transition, FAQ answers open and closes abruptly. 

### Expected behavior

The font color should be black so that answer is clearly visible to the users.

Also, like other FAQs, the arrow should rotate 180 degree for better view.
Smooth transition can be applied.

### Add ScreenShots

<img width="1362" alt="Screenshot 2024-10-12 at 6 35 28 PM" src="https://github.com/user-attachments/assets/1beaf2ad-1701-4881-86be-68469e8c90e1">

Please do let me know if the issue is assigned to me.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by saumyayadav25** [comment]
@Trisha-tech kindly review this issue and do let me know if it is assigned to me.

**Comment by saumyayadav25** [comment]
@Trisha-tech kindly review this issue and do let me know if it is assigned to me

**Comment by saumyayadav25** [comment]
@Trisha-tech kindly review this issue and do let me know if it will be assigned to me?

**Comment by naitikhoriya1** [comment]
You may assign this project task to me . I will do it perfectly as soon I can
