### ISSUE TITLE
[Bug]: CORS Policy Error During Customer Registration

### ISSUE THREAD

**Issue by skanarul8002** [Trisha-tech/OnlineBookSales#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The CORS policy blocks the request when trying to register a new customer. The error message is: No 'Access-Control-Allow-Origin' header is present on the requested resource, causing the request to fail with the status ERR_FAILED.

### Expected behavior

The customer registration request should successfully pass the preflight check and complete the registration without being blocked by the CORS policy.

### Add ScreenShots

i faced this problem, please assign me
![Screenshot 2024-10-14 173902](https://github.com/user-attachments/assets/2f6b54c8-749d-4cfd-9ed8-f34a6551e8ea)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> The CORS policy blocks the request when trying to register a new customer. The error message is: No 'Access-Control-Allow-Origin' header is present on the requested resource, causing the request to fail with the status ERR_FAILED.
> 
> ### Expected behavior
> The customer registration request should successfully pass the preflight check and complete the registration without being blocked by the CORS policy.
> 
> ### Add ScreenShots
> i faced this problem, please assign me ![Screenshot 2024-10-14 173902](https://private-user-images.githubusercontent.com/112712827/376234247-2f6b54c8-749d-4cfd-9ed8-f34a6551e8ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDkzODAsIm5iZiI6MTcyODkwOTA4MCwicGF0aCI6Ii8xMTI3MTI4MjcvMzc2MjM0MjQ3LTJmNmI1NGM4LTc0OWQtNGNmZC05ZWQ4LWYzNGE2NTUxZThlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMjMxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTU3MTgyNDRhZWRhNThjNjEzZTdiNDczMjU3ZjMyYTRkNGFiNDFiMjVkMGE3NzE1MzNmMGY4ZTEwZTdhODZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wss-DrCjsZEFXwrpgj9v8WBSPI1Dlgp6SSY1yxgGfrI)
> 
> ### On which device are you experiencing this bug?
> Chrome, Windows
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @skanarul8002, Go for it
All the Best

**Comment by skanarul8002** [comment]
Hi @Trisha-tech , can you please add the "hacktoberfest-accepted" label also to this PR as it is part of Hacktoberfest? Thank you!
