### ISSUE TITLE
Navbar Enhancements and UI Improvements

### ISSUE THREAD

**Issue by sezallagwal** [Trisha-tech/OnlineBookSales#484]
Description: We are looking to enhance the navbar functionality and improve the overall user experience. This issue covers the following tasks:

Move Search Bar to Navbar:

1. Relocate the search bar from below the navbar to within the navbar itself, positioned to the right of the logo but before the other icons (Login, Cart, Wishlist, etc.).
2. Ensure the search bar remains responsive and fits seamlessly into the design across different screen sizes.

Conditional Display of Icons:

1. When the user is logged out, only show the Login and Cart icons.
2. Once logged in, replace the Login icon with a Profile icon and display additional icons for Wishlist and Orders alongside the Cart icon.
3. Implement smooth transitions for conditional rendering of these icons without affecting the layout.

Highlight Active Page:

1. Add a visual indicator (e.g., background color change, underline, or text color change) to highlight the currently active page in the navbar (e.g., Home, Shop, Wishlist, etc.).
2. Ensure the highlighting is clear and maintains consistency across different pages.

Add Tooltip for Dark Mode Toggle:

1. Include a tooltip for the Dark Mode toggle (moon icon) with the text "Toggle Dark Mode" when hovered.
2. The icon should change between a moon and a sun depending on the mode, with the tooltip reflecting this change.
3. Ensure the dark mode toggle is functional and user-friendly.

Acceptance Criteria:

 1. Search bar is moved to the navbar and is responsive.
 2. Icons are conditionally displayed based on login status.
 3. Active page in the navbar is visually highlighted.
 4. Tooltip for the dark mode toggle is added and functional.

**Comment by Trisha-tech** [comment]
> Description: We are looking to enhance the navbar functionality and improve the overall user experience. This issue covers the following tasks:
> 
> Move Search Bar to Navbar:
> 
> 1. Relocate the search bar from below the navbar to within the navbar itself, positioned to the right of the logo but before the other icons (Login, Cart, Wishlist, etc.).
> 2. Ensure the search bar remains responsive and fits seamlessly into the design across different screen sizes.
> 
> Conditional Display of Icons:
> 
> 1. When the user is logged out, only show the Login and Cart icons.
> 2. Once logged in, replace the Login icon with a Profile icon and display additional icons for Wishlist and Orders alongside the Cart icon.
> 3. Implement smooth transitions for conditional rendering of these icons without affecting the layout.
> 
> Highlight Active Page:
> 
> 1. Add a visual indicator (e.g., background color change, underline, or text color change) to highlight the currently active page in the navbar (e.g., Home, Shop, Wishlist, etc.).
> 2. Ensure the highlighting is clear and maintains consistency across different pages.
> 
> Add Tooltip for Dark Mode Toggle:
> 
> 1. Include a tooltip for the Dark Mode toggle (moon icon) with the text "Toggle Dark Mode" when hovered.
> 2. The icon should change between a moon and a sun depending on the mode, with the tooltip reflecting this change.
> 3. Ensure the dark mode toggle is functional and user-friendly.
> 
> Acceptance Criteria:
> 
> 1. Search bar is moved to the navbar and is responsive.
> 2. Icons are conditionally displayed based on login status.
> 3. Active page in the navbar is visually highlighted.
> 4. Tooltip for the dark mode toggle is added and functional.

Hello @sezallagwal, Go for it
All the Best

**Comment by anchalchaturvedi08** [comment]
@Trisha-tech I also want to work on this task, Can you assign me this too?
