### ISSUE TITLE
[Feature Request]: Adding input validations

### ISSUE THREAD

**Issue by Gauravtb2253** [Trisha-tech/OnlineBookSales#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add proper input form validation to the login and signup pages

### Use Case

It will help to pass valid data to the backend

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> I would like to add proper input form validation to the login and signup pages
> 
> ### Use Case
> It will help to pass valid data to the backend
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Gauravtb2253, Go for it
All the Best
