### ISSUE TITLE
Login Form Data Mislabeling

### ISSUE THREAD

**Issue by ASHISH-JHA94** [Trisha-tech/OnlineBookSales#51]
**Description:**
On the login page, the form asks for the user's name, but upon submission, it requires the user's email for verification. This inconsistency in the labeling of the form fields could confuse new users, leading to login difficulties and potentially discouraging them from completing the login process.

**Steps to Reproduce:**

1.Visit the login page.
2.Observe that the form prompts for the user's name.
3.Enter a name into the provided field.
4.Attempt to submit the form.
5.need to guess by own that it requires email.
Expected Behavior:
The form should accurately label the fields required for login. If the email address is needed for verification, it should be clearly specified on the form.

**Impact:**
This inconsistency in labeling could lead to user confusion, frustration, and abandonment of the login process. It may result in a negative user experience and potential loss of user engagement.

**Proposed Solution:**

Update the login form labels to accurately reflect the information required for login and verification.
Clearly indicate the need for an email address for verification purposes on the form.
Ensure that the user interface provides clear instructions to guide users through the login process without confusion.
**Attachments:**
![Screenshot 2024-05-12 181758](https://github.com/Trisha-tech/OnlineBookSales/assets/136432304/69c88b5e-26da-4ebb-b8f1-5db8d372ae38)

**Comment by Trisha-tech** [comment]
> **Description:** On the login page, the form asks for the user's name, but upon submission, it requires the user's email for verification. This inconsistency in the labeling of the form fields could confuse new users, leading to login difficulties and potentially discouraging them from completing the login process.
> 
> **Steps to Reproduce:**
> 
> 1.Visit the login page. 2.Observe that the form prompts for the user's name. 3.Enter a name into the provided field. 4.Attempt to submit the form. 5.need to guess by own that it requires email. Expected Behavior: The form should accurately label the fields required for login. If the email address is needed for verification, it should be clearly specified on the form.
> 
> **Impact:** This inconsistency in labeling could lead to user confusion, frustration, and abandonment of the login process. It may result in a negative user experience and potential loss of user engagement.
> 
> **Proposed Solution:**
> 
> Update the login form labels to accurately reflect the information required for login and verification. Clearly indicate the need for an email address for verification purposes on the form. Ensure that the user interface provides clear instructions to guide users through the login process without confusion. **Attachments:** ![Screenshot 2024-05-12 181758](https://private-user-images.githubusercontent.com/136432304/329850800-69c88b5e-26da-4ebb-b8f1-5db8d372ae38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MzE5NzIsIm5iZiI6MTcxNTUzMTY3MiwicGF0aCI6Ii8xMzY0MzIzMDQvMzI5ODUwODAwLTY5Yzg4YjVlLTI2ZGEtNGViYi1iOGYxLTVkYjhkMzcyYWUzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxNjM0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzNjNmUwZDcxOThmMTRlM2FhZTgxZGZhNDg1NTg3NGVkZWYzN2Y3N2YwYzAwM2Y1MjZiMjUyYjhiMjU4NDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kE51r3wB0xa4MJ_Cu_FHXJqMWTUw8IcBDDt6s8uX5PU)

Hello @ASHISH-JHA94 , Go for it
All the Best

**Comment by ASHISH-JHA94** [comment]
you can close the issue #51
