### ISSUE TITLE
[Feature Request]: Missing Progress Bar and Hamburger Functionality on Pages

### ISSUE THREAD

**Issue by srishti023** [Trisha-tech/OnlineBookSales#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

mplement a progress bar at the top of each page to visually indicate the user's scroll position, enhancing navigation and user experience. Additionally, create a responsive hamburger menu that drops down from the top when clicked, allowing easy access to navigation links on mobile devices.

### Use Case

Implementing the progress bar and hamburger menu would significantly improve user experience by:

The hamburger menu provides a clean, organized way to access navigation links, especially on mobile devices, making it easier for users to explore content without clutter.

The progress bar gives users immediate visual feedback on their scrolling position, enhancing engagement and encouraging them to explore more of the page.

Both features contribute to a modern, responsive design, ensuring accessibility and usability across various devices, which can lead to increased user retention and satisfaction.

### Add ScreenShots

No progressbar:

![Screenshot 2024-10-16 192824](https://github.com/user-attachments/assets/51311835-240a-481c-9b3b-ad2a2681b364)

No hamburger:

![Screenshot 2024-10-16 192848](https://github.com/user-attachments/assets/edb6cc40-1a94-4492-b675-8fb3e107f9da)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> mplement a progress bar at the top of each page to visually indicate the user's scroll position, enhancing navigation and user experience. Additionally, create a responsive hamburger menu that drops down from the top when clicked, allowing easy access to navigation links on mobile devices.
> 
> ### Use Case
> Implementing the progress bar and hamburger menu would significantly improve user experience by:
> 
> The hamburger menu provides a clean, organized way to access navigation links, especially on mobile devices, making it easier for users to explore content without clutter.
> 
> The progress bar gives users immediate visual feedback on their scrolling position, enhancing engagement and encouraging them to explore more of the page.
> 
> Both features contribute to a modern, responsive design, ensuring accessibility and usability across various devices, which can lead to increased user retention and satisfaction.
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> No progressbar:
> 
> ![Screenshot 2024-10-16 192824](https://private-user-images.githubusercontent.com/137069939/377086064-51311835-240a-481c-9b3b-ad2a2681b364.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzk3ODEsIm5iZiI6MTcyOTIzOTQ4MSwicGF0aCI6Ii8xMzcwNjk5MzkvMzc3MDg2MDY0LTUxMzExODM1LTI0MGEtNDgxYy05YjNiLWFkMmEyNjgxYjM2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwODE4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDZmNjk1NDc4OGFhNDJkNGQ1YWEwOTA4NmI0MzFlM2FkZWNjODU5ZTY1MDRmYmZlZTM4MjlkYWE4M2Q3NmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._q7zvHPH5wwmtTb_2iRcBSG0JYZf6WQPDlHX2a0LQqY)
> 
> No hamburger:
> 
> ![Screenshot 2024-10-16 192848](https://private-user-images.githubusercontent.com/137069939/377086076-edb6cc40-1a94-4492-b675-8fb3e107f9da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzk3ODEsIm5iZiI6MTcyOTIzOTQ4MSwicGF0aCI6Ii8xMzcwNjk5MzkvMzc3MDg2MDc2LWVkYjZjYzQwLTFhOTQtNDQ5Mi1iNjc1LThmYjNlMTA3ZjlkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwODE4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjIwNWE2N2MzZDVlN2M2NmMwNWFiNDliNjkyZTA4YTc2ZDIxYWJlMmIyNDQ3NmFmY2QxZGNmMmZlOTE5ODgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b152MlruAmt9EKIJdUPHZt-Bs3lrUx-3n6zKP1mwAa0)
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @srishti023, Go for it
All the Best
