### ISSUE TITLE
[Feature Request]: Implementation of Google Books API on search bar

### ISSUE THREAD

**Issue by amitroy-thedev** [Trisha-tech/OnlineBookSales#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently the search bar is not searching anything what if we add google books api to search books
![image](https://github.com/user-attachments/assets/ad3a98de-b964-449b-b5a8-e760f83264ff)

@Trisha-tech Assign me i want to work on this feature under gssoc-ext, also please level it as level3

### Use Case

Help user to search books over the internet

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> Currently the search bar is not searching anything what if we add google books api to search books ![image](https://private-user-images.githubusercontent.com/104709542/377538303-ad3a98de-b964-449b-b5a8-e760f83264ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDIzNDEsIm5iZiI6MTcyOTI0MjA0MSwicGF0aCI6Ii8xMDQ3MDk1NDIvMzc3NTM4MzAzLWFkM2E5OGRlLWI5NjQtNDQ5Yi1iNWE4LWU3NjBmODMyNjRmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwOTAwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Yjc3YjdlOWM4MjRhZTRjZmMxMjMwOTU5OGJkY2U0ODc0MjhiMjk4YmQ1YmNmNDRhMGIyNWM3ZmU1ZDhhN2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CIfodahVeG-7uvx1sCeKgSqgiRCljGAcmrpPVanIg58)
> 
> @Trisha-tech Assign me i want to work on this feature under gssoc-ext, also please level it as level3
> 
> ### Use Case
> Help user to search books over the internet
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @amitroy-thedev, Go for it
All the Best
