### ISSUE TITLE
Want to add rounting to the project

### ISSUE THREAD

**Issue by ArtiGaund** [Trisha-tech/OnlineBookSales#53]
I want to add routing between the pages so that different pages can be navigated through url

**Comment by Trisha-tech** [comment]
> I want to add routing between the pages so that different pages can be navigated through url

Go for it @ArtiGaund 
All the Best

**Comment by TusharKumar0907** [comment]
I also want to add routing between the pages . Can you please assign it to me also ?

**Comment by ArtiGaund** [comment]
Routing done
