### ISSUE TITLE
[Feature Request]: Working in New Arrivals Section to generate random books

### ISSUE THREAD

**Issue by Lanaanvar** [Trisha-tech/OnlineBookSales#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I went through the frontend code for the New Arrivals section and found that the book details are hard coded. I would like to change it so that randoms real book details are generated ( maybe using API such as Google books api )

### Use Case

This is useful while searching for the new books arrived in the market. There is no need to update manually since there is an api.

### Benefits

Hardcoding book names could be avoided.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by amitroy-thedev** [comment]
i've made the same issue before you #528 and also made a pr which got conflict which i resolve too

**Comment by Trisha-tech** [comment]
> i've made the same issue before you #528 and also made a pr #562 which got conflict which i resolve too

She had worked on different issue. She had added Google Books API in New Arrivals Section and code is working fine. @amitroy-thedev
