### ISSUE TITLE
[Bug]: Improve the styling of toggle button 

### ISSUE THREAD

**Issue by sayanp607** [Trisha-tech/OnlineBookSales#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The color of the toggle button make it disappear in the header background color(top right corner).
![Screenshot 2024-10-19 102930](https://github.com/user-attachments/assets/c08c1ae7-38ea-4329-9d10-e9bd4a46c2be)

### Expected behavior

I will change the styling of the button , so that user can easily find it out in case of small screens. Please assign this task to me.

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> The color of the toggle button make it disappear in the header background color(top right corner). ![Screenshot 2024-10-19 102930](https://private-user-images.githubusercontent.com/170846702/378050803-c08c1ae7-38ea-4329-9d10-e9bd4a46c2be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDAzNjcsIm5iZiI6MTcyOTM0MDA2NywicGF0aCI6Ii8xNzA4NDY3MDIvMzc4MDUwODAzLWMwOGMxYWU3LTM4ZWEtNDMyOS05ZDEwLWU5YmQ0YTQ2YzJiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMjE0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWI5ZjdiMjhiNzJhMDRmYjBjMWFhNDczNGI2MTdmYmQ5MDcwZTNmNjI3ZTBlY2RjYzVjODc2NzEyMDYwODVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iLy0SuVqdI7c_LTDvqCOXM-8ISe_vfBqX6HLQOl4_so)
> 
> ### Expected behavior
> I will change the styling of the button , so that user can easily find it out in case of small screens. Please assign this task to me.
> 
> ### Add ScreenShots
> _No response_
> 
> ### On which device are you experiencing this bug?
> Chrome
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @sayanp607, Go for it
All the Best

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.
