### ISSUE TITLE
[Bug]:  DARK mode inconsistency throughout website

### ISSUE THREAD

**Issue by Sourabh782** [Trisha-tech/OnlineBookSales#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently there is dark mode inconsistency across different pages, i wanted to resolve dark mode issue through out pages

### Expected behavior

the application should consist of proper dark mode implementation

### Add ScreenShots

![dark](https://github.com/user-attachments/assets/4a85ec3e-5cee-4e85-b12c-db45a1cb44c4)
![dark](https://github.com/user-attachments/assets/e4735526-5ed0-4536-8c9d-5afc9adf2fc6)
![Screenshot 2024-10-19 215938](https://github.com/user-attachments/assets/f0f7e8f9-7e09-467b-959f-64ee89804b01)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by gourabbistu089** [comment]
i will solve this issue

**Comment by himasnhu018** [comment]
I would like to contribute on this as i am good full stack developer. please assign me that issue.

**Comment by gourabbistu089** [comment]
assign me as I am not bad full stack developer

**Comment by Sourabh782** [comment]
@himasnhu018 @gourabbistu089 the issue will be assigned to the one who raised the issue 😊

**Comment by Sourabh782** [comment]
@Trisha-tech can you check this?

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> Currently there is dark mode inconsistency across different pages, i wanted to resolve dark mode issue through out pages
> 
> ### Expected behavior
> the application should consist of proper dark mode implementation
> 
> ### Add ScreenShots
> ![dark](https://private-user-images.githubusercontent.com/103349890/378105093-4a85ec3e-5cee-4e85-b12c-db45a1cb44c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODk0MjgsIm5iZiI6MTcyOTU4OTEyOCwicGF0aCI6Ii8xMDMzNDk4OTAvMzc4MTA1MDkzLTRhODVlYzNlLTVjZWUtNGU4NS1iMTJjLWRiNDVhMWNiNDRjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwOTI1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWUwNzdmNjdhZTQyZmRkNGZkOTAyNGJmZDMzMmVmOGQzZDg0MGEzYWEyMmI3NzkwOTczNThjYjM0NDM3M2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FqwOI7r4X0QmZZljbZ9WpaUjZaMjccZKWfy_i4-IsvM) ![dark](https://private-user-images.githubusercontent.com/103349890/378105125-e4735526-5ed0-4536-8c9d-5afc9adf2fc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODk0MjgsIm5iZiI6MTcyOTU4OTEyOCwicGF0aCI6Ii8xMDMzNDk4OTAvMzc4MTA1MTI1LWU0NzM1NTI2LTVlZDAtNDUzNi04YzlkLTVhZmM5YWRmMmZjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwOTI1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmVkOGRkOTFiOTgzYmYyZDBmZTlkNDZkODFmM2JlOTI5NTQzYzI4ZGFlZTViOTBiOGYwNTk3NjQwZjAwZjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uJmeZmlet7Ag4QQExaoveix3TSk_TGvMjve5wSs3FGE) ![Screenshot 2024-10-19 215938](https://private-user-images.githubusercontent.com/103349890/378105168-f0f7e8f9-7e09-467b-959f-64ee89804b01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODk0MjgsIm5iZiI6MTcyOTU4OTEyOCwicGF0aCI6Ii8xMDMzNDk4OTAvMzc4MTA1MTY4LWYwZjdlOGY5LTdlMDktNDY3Yi05NTlmLTY0ZWU4OTgwNGIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwOTI1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjI4YmVkODc4OWExMWE4NTY0NjA3NjJjM2I3NzA5YTI5MWIzMjk0MGY3MGFjZjc0YWNjMWMzYzJkMDdjNjRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rmyAINx9br2qYfbQzudjvYzdlVc5v_T_nRdigLxc3NQ)
> 
> ### On which device are you experiencing this bug?
> Windows
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @Sourabh782, Go for it
All the Best
