### ISSUE TITLE
[Feature Request]: Adding search filter in search bar.

### ISSUE THREAD

**Issue by sayanp607** [Trisha-tech/OnlineBookSales#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

search bar will contain search filter , so that when user will search, results will appear.

### Use Case

when user type some book type or name, if it exists in the website, it will show as a suggestion and on clicking it, user can see the exact book.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Feature Description
> search bar will contain search filter , so that when user will search, results will appear.
> 
> ### Use Case
> when user type some book type or name, if it exists in the website, it will show as a suggestion and on clicking it, user can see the exact book.
> 
> ### Benefits
> _No response_
> 
> ### Add ScreenShots
> _No response_
> 
> ### Priority
> High
> 
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @sayanp607, Go for it
All the Best
