### ISSUE TITLE
[Bug]: improvement in subscribe button

### ISSUE THREAD

**Issue by officeneerajsaini** [Trisha-tech/OnlineBookSales#594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the footer section at the bottom of the newsletter section, Subscribe button looks odd, I think we can 

<img width="432" alt="Screenshot 2024-10-22 at 9 12 19 PM" src="https://github.com/user-attachments/assets/107720ec-617c-43c6-b075-6a325282e4d3">
improve that button's UI

### Expected behavior

<img width="432" alt="Screenshot 2024-10-22 at 9 11 51 PM" src="https://github.com/user-attachments/assets/ef98dff3-7842-4743-af31-4bb47d2fc2f6">

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by officeneerajsaini** [comment]
@Suman373 Please review my issue. If it is valid, please add the labels gssoc24 extend and Hacktoberfest and assign it to me.

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> In the footer section at the bottom of the newsletter section, Subscribe button looks odd, I think we can
> 
> <img alt="Screenshot 2024-10-22 at 9 12 19 PM" width="432" src="https://private-user-images.githubusercontent.com/118799941/378916892-107720ec-617c-43c6-b075-6a325282e4d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzMwMjYsIm5iZiI6MTcyOTY3MjcyNiwicGF0aCI6Ii8xMTg3OTk5NDEvMzc4OTE2ODkyLTEwNzcyMGVjLTYxN2MtNDNjNi1iMDc1LTZhMzI1MjgyZTRkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwODM4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTVhMzI4OWZmNjk5ZmE5Yzk3MzMyOTI4YmMxYzY2ZjFiMmYyNDY1ZmVlYTQwNzJmMTc5MWM0YjZmYjVkODNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lVVrv6JqWQe2ADWS-5nKoWHWtrBndJxxlgd--CDctTs"> improve that button's UI
> ### Expected behavior
> <img alt="Screenshot 2024-10-22 at 9 11 51 PM" width="432" src="https://private-user-images.githubusercontent.com/118799941/378916724-ef98dff3-7842-4743-af31-4bb47d2fc2f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzMwMjYsIm5iZiI6MTcyOTY3MjcyNiwicGF0aCI6Ii8xMTg3OTk5NDEvMzc4OTE2NzI0LWVmOThkZmYzLTc4NDItNDc0My1hZjMxLTRiYjQ3ZDJmYzJmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwODM4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWY1MjIyYTM2NmMwNzUwNmYzZjFiMzc2MTM4MTg4M2U4Mzc1MThiYWRhNDllY2E0MjE0OGU2NjEyNDNiMjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UVzKIcHP_PUQI9-vG_mcAtSd9sWC3-_mXOVk596fMPs">
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @officeneerajsaini, Go for it
All the Best
