### ISSUE TITLE
[Bug]: Menu Options Underline Remove from Links

### ISSUE THREAD

**Issue by officeneerajsaini** [Trisha-tech/OnlineBookSales#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the menu options, the text content has underlines, which doesn't look good. We can improve the appearance of our header section to make it look better.

<img width="1432" alt="Screenshot 2024-10-22 at 9 13 06 PM" src="https://github.com/user-attachments/assets/f2785021-2fb4-477c-ab5d-5802618e05fd">

### Expected behavior

<img width="1432" alt="Screenshot 2024-10-22 at 9 14 51 PM" src="https://github.com/user-attachments/assets/2d492856-459d-4961-b55c-110f22e57aa0">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by officeneerajsaini** [comment]
@Suman373 Please review my issue. If it is valid, please add the labels gssoc24 extend and Hacktoberfest and assign it to me.

**Comment by Trisha-tech** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> In the menu options, the text content has underlines, which doesn't look good. We can improve the appearance of our header section to make it look better.
> 
> <img alt="Screenshot 2024-10-22 at 9 13 06 PM" width="1432" src="https://private-user-images.githubusercontent.com/118799941/378920757-f2785021-2fb4-477c-ab5d-5802618e05fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzI5NjgsIm5iZiI6MTcyOTY3MjY2OCwicGF0aCI6Ii8xMTg3OTk5NDEvMzc4OTIwNzU3LWYyNzg1MDIxLTJmYjQtNDc3Yy1hYjVkLTU4MDI2MThlMDVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwODM3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWYwN2U5NjRmNzEyYTFhMzU0NWYyMTk4MzY1MWVkZmRhM2YxMDZhOTkxYmQ4NDRkYjZiZDYwMDFmOTk2Y2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ci3p9V6_nOxEhI-2orv6WTooghjnzBe2mE7fnGEddU8">
> ### Expected behavior
> <img alt="Screenshot 2024-10-22 at 9 14 51 PM" width="1432" src="https://private-user-images.githubusercontent.com/118799941/378920313-2d492856-459d-4961-b55c-110f22e57aa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzI5NjgsIm5iZiI6MTcyOTY3MjY2OCwicGF0aCI6Ii8xMTg3OTk5NDEvMzc4OTIwMzEzLTJkNDkyODU2LTQ1OWQtNDk2MS1iNTVjLTExMGYyMmU1N2FhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwODM3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjUzYjBjYzgxZDE2MjU2MzI5MjgyNDE4ZDgzZjJmYTY3NjY4OWNkMWQ0MzE4NmEwMmU2YjZkN2I1NjkxOGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iCg5zqYQcqdIaRqAyjUXV5dCpTi2SyndbJGnilUBBIY">
> ### Record
> * [x]  I have read the Contributing Guidelines
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I have starred the repository

Hello @officeneerajsaini, Go for it
All the Best

**Comment by muskiagrwal** [comment]
i want to work on this proj can u assign me

**Comment by Suman373** [comment]
> i want to work on this proj can u assign me

If you want to contribute to this project go through the contribution guidelines. Then look for issues that has no assignee or create it yourself and tag me or the PA. All the best !

**Comment by muskiagrwal** [comment]
done

**Comment by muskiagrwal** [comment]
requested pull request but #629 gssoc extd # is not visible on pr

**Comment by muskiagrwal** [comment]
please add gssoc extd lable in #629
