### ISSUE TITLE
[Feature Request]: Move "About Us" Option from Footer to Header Navigation for Better Usability

### ISSUE THREAD

**Issue by khushi1315** [Trisha-tech/OnlineBookSales#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "About Us" link is currently located in the footer, which may not provide optimal visibility for users. It's important for users to easily access key information about the organization without scrolling to the bottom of the page. 
Kindly assign me this work under gssoc-ext, hactoberfest24 and level of your choice.

### Use Case

- Improved user experience.
- Easier Navigation.
- Increased visibility.

### Benefits

1. Enhanced User Accessibility
2. Improves Site Navigation
3. Aligns with User Expectations

### Add ScreenShots

<img width="929" alt="Screenshot 2024-10-23 225334" src="https://github.com/user-attachments/assets/371edff0-5b45-4523-82eb-6d8062088877">

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by shaurya35** [comment]
@khushi1315 I think for this project, its suited there in the footer, please open another issue if you have any better idea
thank you for the suggestion
