### ISSUE TITLE
Enhancements: Structured File Organization, Standardized Coding Approach, Home Page, Token-based Authentication

### ISSUE THREAD

**Issue by ASHISH-JHA94** [Trisha-tech/OnlineBookSales#61]
<h2>Title: Enhancements: Structured File Organization, Standardized Coding Approach, Home Page, Token-based Authentication</h2>
  <h3>Summary:</h3>
  <p>Structured file organization, standardized coding approach, added home page, implemented token-based authentication for login.</p>
  <h3>Description:</h3>
  <p>I've made several improvements to the project:</p>
  <ol>
    <li><strong>Structured File Organization:</strong> The files are organized in a structured manner, enhancing navigation and understanding.</li>
    <li><strong>Standardized Coding Approach:</strong> Followed a standard coding approach to improve readability and maintainability.</li>
    <li><strong>Added Home Page:</strong> Implemented a home page and ensured users are redirected back to it after login, improving the user experience.</li>
    <li><strong>Token for Login:</strong> Implemented token-based authentication for login, setting the groundwork for future authentication-related functionalities.</li>
  </ol>
  <h3>Additional Notes:</h3>
  <ul>
    <li>Navbar and footer styling are pending and will be addressed in future updates.</li>
    <li>The token implementation provides a foundation for future authentication-related features.</li>
  </ul>

https://github.com/Trisha-tech/OnlineBookSales/assets/136432304/aeaffb79-bd7c-452d-9db7-8f7740548e45

<h3>Should i raise PR</h3>

**Comment by Trisha-tech** [comment]
> ## Title: Enhancements: Structured File Organization, Standardized Coding Approach, Home Page, Token-based Authentication
> ### Summary:
> Structured file organization, standardized coding approach, added home page, implemented token-based authentication for login.
> 
> ### Description:
> I've made several improvements to the project:
> 
> 1. **Structured File Organization:** The files are organized in a structured manner, enhancing navigation and understanding.
> 2. **Standardized Coding Approach:** Followed a standard coding approach to improve readability and maintainability.
> 3. **Added Home Page:** Implemented a home page and ensured users are redirected back to it after login, improving the user experience.
> 4. **Token for Login:** Implemented token-based authentication for login, setting the groundwork for future authentication-related functionalities.
> 
> ### Additional Notes:
> * Navbar and footer styling are pending and will be addressed in future updates.
> * The token implementation provides a foundation for future authentication-related features.
> 
>  Untitled.video.-.Made.with.Clipchamp.mp4 
> ### Should i raise PR

Hello @ASHISH-JHA94 , Make the PR, make sure there should not be any conflicts
All the best
