### ISSUE TITLE
Adding the merices table

### ISSUE THREAD

**Issue by Aman-G-upta** [Trisha-tech/OnlineBookSales#624]
Adding the merices table to the readme file
@Trisha-tech , please assign me under this issue !!!

![Screenshot 2024-10-26 185138](https://github.com/user-attachments/assets/832300d1-c1c9-4109-8d6d-e9fecf5286b3)

**Comment by shaurya35** [comment]
@Aman-G-upta not really needed, please create new issue if you have any other idea in mind
