### ISSUE TITLE
[Bug]: Book categories cards are not responsive

### ISSUE THREAD

**Issue by Hemraj-7** [Trisha-tech/OnlineBookSales#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Book categories cards are not responsive and these are not align fine.  this issue is occurred in small devices

![Screenshot 2024-10-27 145510](https://github.com/user-attachments/assets/be98c5ba-3749-473d-a1b8-fbb217231969)

### Expected behavior

I want to add margin in the cards and make it better looking. and use text align in the first card it is not align center.

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by shaurya35** [comment]
@Hemraj-7 go ahead with it
