### ISSUE TITLE
[Feature Request]: IMPLEMENTING PURE TAILWIND CSS (REMOVING CSS FILES)

### ISSUE THREAD

**Issue by Sourabh782** [Trisha-tech/OnlineBookSales#628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As we are using tailwind css, there is no need of external css file. so i suggest removing external css file and implementing those classes usinf tailwind css

### Use Case

Tailwind helps us to define minimal css file, and gives us only necessary css, removing unwanted or repeaded styles

### Benefits

improves network overhead, ultimately improving performance and load time of website

### Add ScreenShots

![Screenshot 2024-10-27 211748](https://github.com/user-attachments/assets/93de9b8d-35d4-409c-b274-30ac1b3db2ef)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by shaurya35** [comment]
@Sourabh782 go ahead, assigned to you
if you could fix it completely, its a level 3

**Comment by Sourabh782** [comment]
> @Sourabh782 go ahead, assigned to you if you could fix it completely, its a level 3

Sure will implement it 👍👍👍

**Comment by shaurya35** [comment]
@Sourabh782 make sure to do it for each and every page and components

**Comment by Sourabh782** [comment]
> @Sourabh782 make sure to do it for each and every page and components

Yupp understood👍👍

**Comment by Sourabh782** [comment]
hello @shaurya35 i have implemented it, and also checked the pages after commenting css import statements. its working as expected. So in PR should i remove css files or make pr with css files not deleted ?
