### ISSUE TITLE
[Bug]: Header logo not functional

### ISSUE THREAD

**Issue by HarshS16** [Trisha-tech/OnlineBookSales#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The header logo shows no functionality on home page.

### Expected behavior

It should take the user back to top.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/766a6ef0-aea4-4703-86b2-e3be61f6f7f3)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by HarshS16** [comment]
Please assign this issue to me for gssoc-extd. I'd be really grateful..

**Comment by shaurya35** [comment]
@HarshS16 its functional, please open another issue if you have anything in mind
