### ISSUE TITLE
Auto label workflow automation🚀 

### ISSUE THREAD

**Issue by amiya-cyber** [Trisha-tech/OnlineBookSales#634]
Description: Create a GitHub Actions workflow that automatically labels new issues  based on their content. This will help categorize and prioritize tasks for better project management.

**note** it will only add two labels hacktoberfest and gssoc ext

please @Trisha-tech  assign this with level 3 label

**Comment by shaurya35** [comment]
@amiya-cyber go ahead with it, assigned to you
