### ISSUE TITLE
[Feature Request]: Enhacing the mouse 

### ISSUE THREAD

**Issue by PrajwalMundargi** [Trisha-tech/OnlineBookSales#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current mouse can be improved so that it can interact with other elements of the website, as the home page looks very plane, customizing the mouse and making it to interact with other elements would make the website look even more attractive. This interaction can be done using the GSAP library.

### Use Case

The home would be look more attractive than the current one.

### Benefits

The plane pages would be more interesting to visit.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by BhavikaPachauri** [comment]
if this issue is open can i work on it

**Comment by mridulsaggi** [comment]
The issue is already resolved
