### ISSUE TITLE
Error Handler for Backend API'S

### ISSUE THREAD

**Issue by JainPriya1234** [Trisha-tech/OnlineBookSales#66]
hey @Trisha-tech , I want to make a general error handler that can handle all types of exceptions and errors in the backend.
So, please assign this issue to me.

**Comment by omneaa** [comment]
HI
 I am a GSSoC'24 contributor 
I can do this and i will use nodejs  
I'd be happy if you assign it to me

**Comment by ekayZ7875** [comment]
Heyy i can help you out with this issue please assign it to me.

**Comment by ekayZ7875** [comment]
Thanks @Trisha-tech for assigning it to me.

**Comment by ekayZ7875** [comment]
Hello @Trisha-tech i have raised the PR #301.Please check it out.
