### ISSUE TITLE
[Documentation Update]: Improve the footer design

### ISSUE THREAD

**Issue by Rashmi-Besra** [Trisha-tech/OnlineBookSales#661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

![Screenshot (497)](https://github.com/user-attachments/assets/716af831-0c2f-45d3-be33-5484875be51b)
The layout of footer can be improved to make it more appealing to the users.

### Suggested Change

Spaces can be added between different sections and links to increase its readability. Social icons can be updated to a convenient size and location. A smaller or lighter font can be used for links .A border can be added around the newsletter box to make it stand out.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Rashmi-Besra** [comment]
Assign me this work to improve the footer.

**Comment by Tanisha0708** [comment]
@Rashmi-Besra  please assign me this i would like to improve in this

**Comment by mridulsaggi** [comment]
The issue is already resolved
