### ISSUE TITLE
[Feature Request]: Margin issue for sections below hero image

### ISSUE THREAD

**Issue by niteshkr100** [Trisha-tech/OnlineBookSales#678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I have found that there is no margin given in left and right side of sections below hero image. This margin issue is existed in both desktop view and mobile view.

### Use Case

By doing this feature improvement, it is enhance the user readability and  make them to focus on content of section more clear.

### Benefits

advantages:
1)enhance user experience.
2)Increase the user engagement in the website.

### Add ScreenShots

<img width="1439" alt="Screenshot 2024-11-06 at 10 13 10 AM" src="https://github.com/user-attachments/assets/d3036aaa-33b9-415b-9b36-42b36ff80467">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by niteshkr100** [comment]
@Trisha-tech Please assign me for this issue.

**Comment by mridulsaggi** [comment]
@niteshkr100 combine some more existing issues along with this and pitch the issue again for getting it assigned to you.

**Comment by niteshkr100** [comment]
I have raise all the feature improvement issue please assign me the task in new raise issue ticket.
