### ISSUE TITLE
[Features Request]: Improve design error of navbar, added padding in section of home page & solve image not shown in book/undefined route page

### ISSUE THREAD

**Issue by niteshkr100** [Trisha-tech/OnlineBookSales#681]
Is there an existing issue for this?
- [X] I have searched the existing issues

## Title
To improve design issue

## Decription
1)Solve the duplicate icon & search bar of navbar in dektop view.
2)Padding/margin is not given properly to give each section like home page look distinct from each other. I  want  to improve user eperience for section of home page.
3)/book/undefined ,  this route page have issue regarding image as image is shown, only able to see image name.
4)/book/undefined , this route page need some design improvement, I want to improve that.

## screenshots
 
<img width="1440" alt="Screenshot 2024-11-06 at 8 23 30 PM" src="https://github.com/user-attachments/assets/e2c9ece7-3c53-44d3-ae39-de7254f8ba7f">

<img width="1439" alt="Screenshot 2024-11-06 at 10 13 10 AM" src="https://github.com/user-attachments/assets/288b401b-099a-4fab-aa67-d342fe006d6a">

<img width="1440" alt="Screenshot 2024-11-06 at 8 13 28 PM" src="https://github.com/user-attachments/assets/2f5d48e1-6b22-496d-b717-d7ede7ee1b16">

<img width="1440" alt="Screenshot 2024-11-06 at 8 11 14 PM" src="https://github.com/user-attachments/assets/a0a012fe-a0a5-4140-ad1f-cafffa333d7f">

 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

@Tisha-tech, please assign me these task  with label.

**Comment by mridulsaggi** [comment]
The issue has already been resolved.
