### ISSUE TITLE
Fix the Signup Validation 

### ISSUE THREAD

**Issue by Trisha-tech** [Trisha-tech/OnlineBookSales#70]
![screenshot-localhost_3000-2024 05 13-20_20_59](https://github.com/Trisha-tech/OnlineBookSales/assets/55338588/574a29f0-48d6-42ce-bfbb-8639582c8b5c)

**Comment by Naman197** [comment]
Could you please assign this issue to me

**Comment by Trisha-tech** [comment]
> Could you please assign this issue to me

Go for it @Naman197 
All the Best

**Comment by ASHISH-JHA94** [comment]
hey @Trisha-tech  i have raised pr, regarding this issue and also corrected sharable link missing import
i need to ask why tailwind styles are not working has it configure correctly ,please check  and tell me.

**Comment by omneaa** [comment]
HI
 I am a GSSoC'24 contributor 
I can do this and i will use nodejs  
I'd be happy if you assign it to me
