### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [Trisha-tech/OnlineBookSales#71]
## Security Feature
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.
Assign me this work under GSSoC24, I will implement it.

**Comment by Trisha-tech** [comment]
> ## Security Feature
> In your application anyone can enter using **temporary or disposable email**. I will add a feature so that no one could create an account using **temporary or disposable email**. It will allow only genuine users in your database. It will help to avoid any bot. Assign me this work under GSSoC24, I will implement it.

Hello @pankaj-bind , Go for it
All the Best

**Comment by Damini2004** [comment]
hello sir @pankaj-bind can you just tell me how will you implement your raised issue. This message is just for knowledge gathering purpose.

**Comment by pankaj-bind** [comment]
> hello sir @pankaj-bind can you just tell me how will you implement your raised issue. This message is just for knowledge gathering purpose.

It is a frontend feature, which I discovered accidently. It won't affect backend. 
I will use an API, which is free it will first checks is the email genuine or not, if yes then it proceeds otherwise, breaks operation and shows a popup "invalid email". 
I have tried this, and this feature is very unique.

**Comment by Damini2004** [comment]
Will you tell me API name

> > hello sir @pankaj-bind can you just tell me how will you implement your raised issue. This message is just for knowledge gathering purpose.
> 
> It is a frontend feature, which I discovered accidently. It won't affect backend. I will use an API, which is free it will first checks is the email genuine or not, if yes then it proceeds otherwise, breaks operation and shows a popup "invalid email". I have tried this, and this feature is very unique.

Will you tell me API name

**Comment by pankaj-bind** [comment]
email me I'll share you code

> Will you tell me API name
> 
> > > hello sir @pankaj-bind can you just tell me how will you implement your raised issue. This message is just for knowledge gathering purpose.
> > 
> > 
> > It is a frontend feature, which I discovered accidently. It won't affect backend. I will use an API, which is free it will first checks is the email genuine or not, if yes then it proceeds otherwise, breaks operation and shows a popup "invalid email". I have tried this, and this feature is very unique.
> 
> Will you tell me API name

email me I'll share you code

**Comment by Damini2004** [comment]
sure thank you sir... 
Email : - daminichachane04@gmail.com

> email me I'll share you code
> 
> > Will you tell me API name
> > > > hello sir @pankaj-bind can you just tell me how will you implement your raised issue. This message is just for knowledge gathering purpose.
> > > 
> > > 
> > > It is a frontend feature, which I discovered accidently. It won't affect backend. I will use an API, which is free it will first checks is the email genuine or not, if yes then it proceeds otherwise, breaks operation and shows a popup "invalid email". I have tried this, and this feature is very unique.
> > 
> > 
> > Will you tell me API name
> 
> email me I'll share you code

**Comment by pankaj-bind** [comment]
@Trisha-tech this issue not completed yet someone tagged it by mistake.
