### ISSUE TITLE
Add GitHub Desktop Contribution Instructions

### ISSUE THREAD

**Issue by PradnyaGaitonde** [Trisha-tech/OnlineBookSales#77]
I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.

I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.

Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others.

**Comment by Trisha-tech** [comment]
> I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.
> 
> I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.
> 
> Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others.

Hello @PradnyaGaitonde  Go for it
All the Best

**Comment by PradnyaGaitonde** [comment]
hello @Trisha-tech Could you please add gssoc24 labels as well as label for level of difficulty of issue solved.
