### ISSUE TITLE
There are 2 navbar in the code

### ISSUE THREAD

**Issue by ArtiGaund** [Trisha-tech/OnlineBookSales#81]
![Screenshot (280)](https://github.com/Trisha-tech/OnlineBookSales/assets/38074085/0fa41804-c06e-4e81-9894-1f3449b4c10a)
There are 2 navbar in the code. 
Header and Navbar

**Comment by Isha1233** [comment]
@ArtiGaund please assign this task to me, I can solve this issue.

**Comment by GnanariddhikaRavikumar** [comment]
@ArtiGaund kindly assign me this issue under GSSOC'24 .I will fix this issue

**Comment by ArtiGaund** [comment]
I am not the mentor, I raised this issue for me, and this issue is already been resolved now. Read the codebase.

**Comment by GnanariddhikaRavikumar** [comment]
Ok... Thank you for your response
