### ISSUE TITLE
Tailwind styles are not applying, needs to fix

### ISSUE THREAD

**Issue by ASHISH-JHA94** [Trisha-tech/OnlineBookSales#87]
while i was working on navbar and footer i findout my tailwind classes are not applying 
needs to fix this issue.

**Comment by Karthikkariappa08** [comment]
Hi @ASHISH-JHA94,
I'm excited to tackle the task of Tailwind styles webpage. With my experience in website development using HTML, CSS, and JavaScript.


Please assign this task to me under GSSoC 24, and I'll get started right away!
Looking forward to your approval and the opportunity to contribute!

Thank you 😊!!
