### ISSUE TITLE
Design of Navbar and footer

### ISSUE THREAD

**Issue by ASHISH-JHA94** [Trisha-tech/OnlineBookSales#89]
need to work on responsive navbar and footer and style it with tailwind

**Comment by Karthikkariappa08** [comment]
Hi ,
I'm excited to tackle the task of Design of Navbar and footer to the webpage. With my experience in website development using HTML, CSS, and JavaScript.


Please assign this task to me under GSSoC 24, and I'll get started right away!
Looking forward to your approval and the opportunity to contribute!

Thank you 😊!!

**Comment by Karthikkariappa08** [comment]
plz add GSSOC-24 Lable to this
