### ISSUE TITLE
Bugs(after all the merge operation done of pull request)

### ISSUE THREAD

**Issue by ArtiGaund** [Trisha-tech/OnlineBookSales#93]
![Screenshot (289)](https://github.com/Trisha-tech/OnlineBookSales/assets/38074085/396552c9-7929-4ad4-961f-98b1feab7900)
These are the errors that occur after merge operations are done for pull requests. 
I pulled the data from upstream to work on my assigned work. These errors occurred when I pulled the current code from the repository, but I have resolved them.

**Comment by Trisha-tech** [comment]
> ![Screenshot (289)](https://private-user-images.githubusercontent.com/38074085/330766973-396552c9-7929-4ad4-961f-98b1feab7900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzM2NDQsIm5iZiI6MTcxNTc3MzM0NCwicGF0aCI6Ii8zODA3NDA4NS8zMzA3NjY5NzMtMzk2NTUyYzktNzkyOS00YWQ0LTk2MWYtOThiMWZlYWI3OTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDExNDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDlkN2YzMzBmNWY4N2ViMTFiNjE2M2I0NGVjZGYzYmNhZGExZmJjNWIzNTY5ZTk2Mzk0ODQ0ZTk3M2M2OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ElhT_sq7TW1gsuI0TK73mJ8DeflgTnmBjV4Xy0kuj3E) These are the errors that occur after merge operations are done for pull requests. I pulled the data from upstream to work on my assigned work. These errors occurred when I pulled the current code from the repository, but I have resolved them.

Okay then again make a PR @ArtiGaund

**Comment by ArtiGaund** [comment]
done

**Comment by ArtiGaund** [comment]
Fixed the error
