### ISSUE TITLE
Create .env.sample file

### ISSUE THREAD

**Issue by gyanendra-baghel** [Trisha-tech/OnlineBookSales#98]
## Why this issue

There are large amount of contributor is working in this project and setup this project.
- First, Every contributor has to find all the environment variables exist in this project. 
- Then make .env file with all ENV variables then start the server.

This .env.sample file contains all the env variables that can be used in this project. That will make easy to setup this project.

@Trisha-tech Can you assign me this project under `gssoc`.

**Comment by Trisha-tech** [comment]
> ## Why this issue
> There are large amount of contributor is working in this project and setup this project.
> 
> * First, Every contributor has to find all the environment variables exist in this project.
> * Then make .env file with all ENV variables then start the server.
> 
> This .env.sample file contains all the env variables that can be used in this project. That will make easy to setup this project.
> 
> @Trisha-tech Can you assign me this project under `gssoc`.

Hello @gyanendra-baghel , Go for it
All the Best

**Comment by gyanendra-baghel** [comment]
Can you this task under `gssoc` with `label1`
