### ISSUE TITLE
Build fail along with bad coding errors

### ISSUE THREAD

**Issue by amit429** [Trisha-tech/OnlineBookSales#99]
The build of the app is failing which needs to be done on priority

![image](https://github.com/Trisha-tech/OnlineBookSales/assets/68067897/fade8dea-6c5f-4968-b1cc-c68b0164bf9f)

need to urgently fix it

Component imports are pushed without any component creation

**Comment by Trisha-tech** [comment]
> @Trisha-tech please look into this , its urgent as the build is failing please assign me the task on priority under gssoc label

Hello @amit429 , Go for it
All the Best

**Comment by gyanendra-baghel** [comment]
@Trisha-tech Frontend Error is not resolved, can you assign me. I will  resolve that error very soon.

**Comment by Trisha-tech** [comment]
> @Trisha-tech Frontend Error is not resolved, can you assign me. I will resolve that error very soon.

Hello @gyanendra-baghel , Go for it
All the Best
